-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_act_read_attn is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_inout1_AWVALID : OUT STD_LOGIC;
    m_axi_inout1_AWREADY : IN STD_LOGIC;
    m_axi_inout1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_WVALID : OUT STD_LOGIC;
    m_axi_inout1_WREADY : IN STD_LOGIC;
    m_axi_inout1_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout1_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout1_WLAST : OUT STD_LOGIC;
    m_axi_inout1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_ARVALID : OUT STD_LOGIC;
    m_axi_inout1_ARREADY : IN STD_LOGIC;
    m_axi_inout1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_RVALID : IN STD_LOGIC;
    m_axi_inout1_RREADY : OUT STD_LOGIC;
    m_axi_inout1_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout1_RLAST : IN STD_LOGIC;
    m_axi_inout1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_inout1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_BVALID : IN STD_LOGIC;
    m_axi_inout1_BREADY : OUT STD_LOGIC;
    m_axi_inout1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    attn_stream_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    attn_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    attn_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    attn_stream_full_n : IN STD_LOGIC;
    attn_stream_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    attn : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of ViT_act_read_attn is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv15_4284 : STD_LOGIC_VECTOR (14 downto 0) := "100001010000100";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv11_204 : STD_LOGIC_VECTOR (10 downto 0) := "01000000100";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln322_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal attn_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal inout1_blk_n_AR : STD_LOGIC;
    signal inout1_blk_n_R : STD_LOGIC;
    signal trunc_ln329_fu_151_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln329_reg_557_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_reg_557_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln329_2_fu_413_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_2_reg_566_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln329_7_reg_571 : STD_LOGIC_VECTOR (58 downto 0);
    signal inout1_addr_read_reg_582 : STD_LOGIC_VECTOR (255 downto 0);
    signal sext_ln329_fu_478_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal q_patch_offset_fu_106 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln326_fu_433_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_q_patch_offset_load : STD_LOGIC_VECTOR (2 downto 0);
    signal k_patch_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln324_1_fu_341_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_k_patch_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_fu_114 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln324_3_fu_445_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (10 downto 0);
    signal q_patch_block_fu_118 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln322_2_fu_295_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_q_patch_block_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten19_fu_122 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln322_1_fu_225_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten19_load : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal shl_ln_fu_201_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln_fu_189_p5 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln329_fu_209_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln324_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln322_fu_237_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln_mid1_fu_257_p5 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln326_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln322_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln322_fu_249_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln322_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln324_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln324_fu_303_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln326_mid1_fu_323_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_1_fu_269_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln329_1_fu_331_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln324_fu_315_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln329_3_fu_335_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln329_fu_213_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_363_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_48_fu_373_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_353_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln322_3_fu_383_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln324_2_fu_391_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln329_1_fu_349_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln2_fu_399_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln329_2_fu_409_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln329_1_fu_417_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln324_1_fu_439_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln329_6_fu_488_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln329_2_fu_495_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln329_1_fu_500_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln329_3_fu_508_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln329_fu_512_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_245 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_act_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component ViT_act_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten19_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_245)) then
                if ((icmp_ln322_fu_219_p2 = ap_const_lv1_0)) then 
                    indvar_flatten19_fu_122 <= add_ln322_1_fu_225_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten19_fu_122 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_245)) then
                if ((icmp_ln322_fu_219_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_114 <= select_ln324_3_fu_445_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_114 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    k_patch_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_245)) then
                if ((icmp_ln322_fu_219_p2 = ap_const_lv1_0)) then 
                    k_patch_fu_110 <= select_ln324_1_fu_341_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_patch_fu_110 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    q_patch_block_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_245)) then
                if ((icmp_ln322_fu_219_p2 = ap_const_lv1_0)) then 
                    q_patch_block_fu_118 <= select_ln322_2_fu_295_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    q_patch_block_fu_118 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    q_patch_offset_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_245)) then
                if ((icmp_ln322_fu_219_p2 = ap_const_lv1_0)) then 
                    q_patch_offset_fu_106 <= add_ln326_fu_433_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    q_patch_offset_fu_106 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln329_2_reg_566_pp0_iter1_reg <= trunc_ln329_2_reg_566;
                trunc_ln329_reg_557 <= trunc_ln329_fu_151_p1;
                trunc_ln329_reg_557_pp0_iter1_reg <= trunc_ln329_reg_557;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                inout1_addr_read_reg_582 <= m_axi_inout1_RDATA;
                trunc_ln329_2_reg_566_pp0_iter2_reg <= trunc_ln329_2_reg_566_pp0_iter1_reg;
                trunc_ln329_2_reg_566_pp0_iter3_reg <= trunc_ln329_2_reg_566_pp0_iter2_reg;
                trunc_ln329_2_reg_566_pp0_iter4_reg <= trunc_ln329_2_reg_566_pp0_iter3_reg;
                trunc_ln329_2_reg_566_pp0_iter5_reg <= trunc_ln329_2_reg_566_pp0_iter4_reg;
                trunc_ln329_2_reg_566_pp0_iter6_reg <= trunc_ln329_2_reg_566_pp0_iter5_reg;
                trunc_ln329_2_reg_566_pp0_iter7_reg <= trunc_ln329_2_reg_566_pp0_iter6_reg;
                trunc_ln329_2_reg_566_pp0_iter8_reg <= trunc_ln329_2_reg_566_pp0_iter7_reg;
                trunc_ln329_reg_557_pp0_iter2_reg <= trunc_ln329_reg_557_pp0_iter1_reg;
                trunc_ln329_reg_557_pp0_iter3_reg <= trunc_ln329_reg_557_pp0_iter2_reg;
                trunc_ln329_reg_557_pp0_iter4_reg <= trunc_ln329_reg_557_pp0_iter3_reg;
                trunc_ln329_reg_557_pp0_iter5_reg <= trunc_ln329_reg_557_pp0_iter4_reg;
                trunc_ln329_reg_557_pp0_iter6_reg <= trunc_ln329_reg_557_pp0_iter5_reg;
                trunc_ln329_reg_557_pp0_iter7_reg <= trunc_ln329_reg_557_pp0_iter6_reg;
                trunc_ln329_reg_557_pp0_iter8_reg <= trunc_ln329_reg_557_pp0_iter7_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln322_fu_219_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln329_2_reg_566 <= trunc_ln329_2_fu_413_p1;
                trunc_ln329_7_reg_571 <= add_ln329_1_fu_417_p2(63 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln322_1_fu_225_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten19_load) + unsigned(ap_const_lv15_1));
    add_ln322_fu_237_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_q_patch_block_2) + unsigned(ap_const_lv6_1));
    add_ln324_1_fu_439_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv11_1));
    add_ln324_fu_303_p2 <= std_logic_vector(unsigned(select_ln322_fu_249_p3) + unsigned(ap_const_lv8_1));
    add_ln326_fu_433_p2 <= std_logic_vector(unsigned(select_ln324_fu_315_p3) + unsigned(ap_const_lv3_1));
    add_ln329_1_fu_417_p2 <= std_logic_vector(unsigned(zext_ln329_2_fu_409_p1) + unsigned(attn));
    add_ln329_2_fu_495_p2 <= std_logic_vector(unsigned(trunc_ln329_6_fu_488_p3) + unsigned(trunc_ln329_reg_557_pp0_iter8_reg));
    add_ln329_3_fu_335_p2 <= std_logic_vector(unsigned(select_ln322_1_fu_269_p3) + unsigned(zext_ln329_1_fu_331_p1));
    add_ln329_fu_213_p2 <= std_logic_vector(unsigned(or_ln_fu_189_p5) + unsigned(zext_ln329_fu_209_p1));
    and_ln322_fu_289_p2 <= (xor_ln322_fu_277_p2 and icmp_ln326_fu_283_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_done_reg, m_axi_inout1_RVALID, attn_stream_full_n, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (attn_stream_full_n = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_inout1_RVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_done_reg, m_axi_inout1_ARREADY, m_axi_inout1_RVALID, attn_stream_full_n, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (attn_stream_full_n = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_inout1_RVALID = ap_const_logic_0)) or ((m_axi_inout1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_done_reg, m_axi_inout1_ARREADY, m_axi_inout1_RVALID, attn_stream_full_n, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (attn_stream_full_n = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_inout1_RVALID = ap_const_logic_0)) or ((m_axi_inout1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(attn_stream_full_n)
    begin
                ap_block_state10_pp0_stage0_iter9 <= (attn_stream_full_n = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter8_assign_proc : process(m_axi_inout1_RVALID)
    begin
                ap_block_state9_pp0_stage0_iter8 <= (m_axi_inout1_RVALID = ap_const_logic_0);
    end process;


    ap_condition_245_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_245 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln322_fu_219_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln322_fu_219_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten19_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten19_fu_122, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten19_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten19_load <= indvar_flatten19_fu_122;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_114, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_114;
        end if; 
    end process;


    ap_sig_allocacmp_k_patch_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_patch_fu_110, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_k_patch_2 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_k_patch_2 <= k_patch_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_q_patch_block_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, q_patch_block_fu_118, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_q_patch_block_2 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_q_patch_block_2 <= q_patch_block_fu_118;
        end if; 
    end process;


    ap_sig_allocacmp_q_patch_offset_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, q_patch_offset_fu_106, ap_loop_init, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_q_patch_offset_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_q_patch_offset_load <= q_patch_offset_fu_106;
        end if; 
    end process;


    attn_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter9, attn_stream_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            attn_stream_blk_n <= attn_stream_full_n;
        else 
            attn_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    attn_stream_din <= lshr_ln329_fu_512_p2(128 - 1 downto 0);

    attn_stream_write_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            attn_stream_write <= ap_const_logic_1;
        else 
            attn_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln322_fu_219_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten19_load = ap_const_lv15_4284) else "0";
    icmp_ln324_fu_243_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv11_204) else "0";
    icmp_ln326_fu_283_p2 <= "1" when (ap_sig_allocacmp_q_patch_offset_load = ap_const_lv3_4) else "0";

    inout1_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_inout1_ARREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            inout1_blk_n_AR <= m_axi_inout1_ARREADY;
        else 
            inout1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    inout1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_inout1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            inout1_blk_n_R <= m_axi_inout1_RVALID;
        else 
            inout1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    lshr_ln329_fu_512_p2 <= std_logic_vector(shift_right(unsigned(inout1_addr_read_reg_582),to_integer(unsigned('0' & zext_ln329_3_fu_508_p1(31-1 downto 0)))));
    m_axi_inout1_ARADDR <= sext_ln329_fu_478_p1;
    m_axi_inout1_ARBURST <= ap_const_lv2_0;
    m_axi_inout1_ARCACHE <= ap_const_lv4_0;
    m_axi_inout1_ARID <= ap_const_lv1_0;
    m_axi_inout1_ARLEN <= ap_const_lv32_1;
    m_axi_inout1_ARLOCK <= ap_const_lv2_0;
    m_axi_inout1_ARPROT <= ap_const_lv3_0;
    m_axi_inout1_ARQOS <= ap_const_lv4_0;
    m_axi_inout1_ARREGION <= ap_const_lv4_0;
    m_axi_inout1_ARSIZE <= ap_const_lv3_0;
    m_axi_inout1_ARUSER <= ap_const_lv1_0;

    m_axi_inout1_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_inout1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_inout1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_inout1_AWADDR <= ap_const_lv64_0;
    m_axi_inout1_AWBURST <= ap_const_lv2_0;
    m_axi_inout1_AWCACHE <= ap_const_lv4_0;
    m_axi_inout1_AWID <= ap_const_lv1_0;
    m_axi_inout1_AWLEN <= ap_const_lv32_0;
    m_axi_inout1_AWLOCK <= ap_const_lv2_0;
    m_axi_inout1_AWPROT <= ap_const_lv3_0;
    m_axi_inout1_AWQOS <= ap_const_lv4_0;
    m_axi_inout1_AWREGION <= ap_const_lv4_0;
    m_axi_inout1_AWSIZE <= ap_const_lv3_0;
    m_axi_inout1_AWUSER <= ap_const_lv1_0;
    m_axi_inout1_AWVALID <= ap_const_logic_0;
    m_axi_inout1_BREADY <= ap_const_logic_0;

    m_axi_inout1_RREADY_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_inout1_RREADY <= ap_const_logic_1;
        else 
            m_axi_inout1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_inout1_WDATA <= ap_const_lv256_lc_1;
    m_axi_inout1_WID <= ap_const_lv1_0;
    m_axi_inout1_WLAST <= ap_const_logic_0;
    m_axi_inout1_WSTRB <= ap_const_lv32_0;
    m_axi_inout1_WUSER <= ap_const_lv1_0;
    m_axi_inout1_WVALID <= ap_const_logic_0;
    or_ln324_fu_309_p2 <= (icmp_ln324_fu_243_p2 or and_ln322_fu_289_p2);
    or_ln_fu_189_p5 <= (((ap_sig_allocacmp_q_patch_block_2 & ap_const_lv1_0) & ap_sig_allocacmp_q_patch_block_2) & ap_const_lv2_0);
    or_ln_mid1_fu_257_p5 <= (((add_ln322_fu_237_p2 & ap_const_lv1_0) & add_ln322_fu_237_p2) & ap_const_lv2_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln322_1_fu_269_p3 <= 
        or_ln_mid1_fu_257_p5 when (icmp_ln324_fu_243_p2(0) = '1') else 
        or_ln_fu_189_p5;
    select_ln322_2_fu_295_p3 <= 
        add_ln322_fu_237_p2 when (icmp_ln324_fu_243_p2(0) = '1') else 
        ap_sig_allocacmp_q_patch_block_2;
    select_ln322_3_fu_383_p3 <= 
        tmp_s_fu_363_p4 when (icmp_ln324_fu_243_p2(0) = '1') else 
        tmp_48_fu_373_p4;
    select_ln322_fu_249_p3 <= 
        ap_const_lv8_0 when (icmp_ln324_fu_243_p2(0) = '1') else 
        ap_sig_allocacmp_k_patch_2;
    select_ln324_1_fu_341_p3 <= 
        add_ln324_fu_303_p2 when (and_ln322_fu_289_p2(0) = '1') else 
        select_ln322_fu_249_p3;
    select_ln324_2_fu_391_p3 <= 
        tmp_fu_353_p4 when (and_ln322_fu_289_p2(0) = '1') else 
        select_ln322_3_fu_383_p3;
    select_ln324_3_fu_445_p3 <= 
        ap_const_lv11_1 when (icmp_ln324_fu_243_p2(0) = '1') else 
        add_ln324_1_fu_439_p2;
    select_ln324_fu_315_p3 <= 
        ap_const_lv3_0 when (or_ln324_fu_309_p2(0) = '1') else 
        ap_sig_allocacmp_q_patch_offset_load;
        sext_ln329_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln329_7_reg_571),64));

    shl_ln2_fu_399_p4 <= ((select_ln324_2_fu_391_p3 & trunc_ln329_1_fu_349_p1) & ap_const_lv4_0);
    shl_ln326_mid1_fu_323_p3 <= (add_ln324_fu_303_p2 & ap_const_lv2_0);
    shl_ln329_1_fu_500_p3 <= (add_ln329_2_fu_495_p2 & ap_const_lv3_0);
    shl_ln_fu_201_p3 <= (ap_sig_allocacmp_k_patch_2 & ap_const_lv2_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_48_fu_373_p4 <= add_ln329_fu_213_p2(14 downto 2);
    tmp_fu_353_p4 <= add_ln329_3_fu_335_p2(14 downto 2);
    tmp_s_fu_363_p4 <= ((add_ln322_fu_237_p2 & ap_const_lv1_0) & add_ln322_fu_237_p2);
    trunc_ln329_1_fu_349_p1 <= select_ln324_fu_315_p3(2 - 1 downto 0);
    trunc_ln329_2_fu_413_p1 <= select_ln324_fu_315_p3(1 - 1 downto 0);
    trunc_ln329_6_fu_488_p3 <= (trunc_ln329_2_reg_566_pp0_iter8_reg & ap_const_lv4_0);
    trunc_ln329_fu_151_p1 <= attn(5 - 1 downto 0);
    xor_ln322_fu_277_p2 <= (icmp_ln324_fu_243_p2 xor ap_const_lv1_1);
    zext_ln329_1_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln326_mid1_fu_323_p3),15));
    zext_ln329_2_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_399_p4),64));
    zext_ln329_3_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln329_1_fu_500_p3),256));
    zext_ln329_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_201_p3),15));
end behav;
