-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_act_compute_attn_matmul_v is
port (
    m_axi_inout2_AWVALID : OUT STD_LOGIC;
    m_axi_inout2_AWREADY : IN STD_LOGIC;
    m_axi_inout2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_WVALID : OUT STD_LOGIC;
    m_axi_inout2_WREADY : IN STD_LOGIC;
    m_axi_inout2_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout2_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout2_WLAST : OUT STD_LOGIC;
    m_axi_inout2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_ARVALID : OUT STD_LOGIC;
    m_axi_inout2_ARREADY : IN STD_LOGIC;
    m_axi_inout2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_RVALID : IN STD_LOGIC;
    m_axi_inout2_RREADY : OUT STD_LOGIC;
    m_axi_inout2_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout2_RLAST : IN STD_LOGIC;
    m_axi_inout2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_inout2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_BVALID : IN STD_LOGIC;
    m_axi_inout2_BREADY : OUT STD_LOGIC;
    m_axi_inout2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    v : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout1_AWVALID : OUT STD_LOGIC;
    m_axi_inout1_AWREADY : IN STD_LOGIC;
    m_axi_inout1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_WVALID : OUT STD_LOGIC;
    m_axi_inout1_WREADY : IN STD_LOGIC;
    m_axi_inout1_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout1_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout1_WLAST : OUT STD_LOGIC;
    m_axi_inout1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_ARVALID : OUT STD_LOGIC;
    m_axi_inout1_ARREADY : IN STD_LOGIC;
    m_axi_inout1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_RVALID : IN STD_LOGIC;
    m_axi_inout1_RREADY : OUT STD_LOGIC;
    m_axi_inout1_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout1_RLAST : IN STD_LOGIC;
    m_axi_inout1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_inout1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_BVALID : IN STD_LOGIC;
    m_axi_inout1_BREADY : OUT STD_LOGIC;
    m_axi_inout1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    attn : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout4_AWVALID : OUT STD_LOGIC;
    m_axi_inout4_AWREADY : IN STD_LOGIC;
    m_axi_inout4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_WVALID : OUT STD_LOGIC;
    m_axi_inout4_WREADY : IN STD_LOGIC;
    m_axi_inout4_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout4_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout4_WLAST : OUT STD_LOGIC;
    m_axi_inout4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_ARVALID : OUT STD_LOGIC;
    m_axi_inout4_ARREADY : IN STD_LOGIC;
    m_axi_inout4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_RVALID : IN STD_LOGIC;
    m_axi_inout4_RREADY : OUT STD_LOGIC;
    m_axi_inout4_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout4_RLAST : IN STD_LOGIC;
    m_axi_inout4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_inout4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_BVALID : IN STD_LOGIC;
    m_axi_inout4_BREADY : OUT STD_LOGIC;
    m_axi_inout4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    attn_softmax_info : IN STD_LOGIC_VECTOR (63 downto 0);
    attn_matmul_v : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    attn_matmul_v_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    v_ap_vld : IN STD_LOGIC;
    attn_ap_vld : IN STD_LOGIC;
    attn_softmax_info_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of ViT_act_compute_attn_matmul_v is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal entry_proc25_U0_ap_start : STD_LOGIC;
    signal entry_proc25_U0_ap_done : STD_LOGIC;
    signal entry_proc25_U0_ap_continue : STD_LOGIC;
    signal entry_proc25_U0_ap_idle : STD_LOGIC;
    signal entry_proc25_U0_ap_ready : STD_LOGIC;
    signal entry_proc25_U0_start_out : STD_LOGIC;
    signal entry_proc25_U0_start_write : STD_LOGIC;
    signal entry_proc25_U0_attn_matmul_v_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc25_U0_attn_matmul_v_c_write : STD_LOGIC;
    signal read_k_v_6_U0_ap_start : STD_LOGIC;
    signal read_k_v_6_U0_ap_done : STD_LOGIC;
    signal read_k_v_6_U0_ap_continue : STD_LOGIC;
    signal read_k_v_6_U0_ap_idle : STD_LOGIC;
    signal read_k_v_6_U0_ap_ready : STD_LOGIC;
    signal read_k_v_6_U0_m_axi_inout2_AWVALID : STD_LOGIC;
    signal read_k_v_6_U0_m_axi_inout2_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_WVALID : STD_LOGIC;
    signal read_k_v_6_U0_m_axi_inout2_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_WLAST : STD_LOGIC;
    signal read_k_v_6_U0_m_axi_inout2_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARVALID : STD_LOGIC;
    signal read_k_v_6_U0_m_axi_inout2_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_k_v_6_U0_m_axi_inout2_RREADY : STD_LOGIC;
    signal read_k_v_6_U0_m_axi_inout2_BREADY : STD_LOGIC;
    signal read_k_v_6_U0_v_stream_din : STD_LOGIC_VECTOR (255 downto 0);
    signal read_k_v_6_U0_v_stream_write : STD_LOGIC;
    signal read_k_v_6_U0_start_out : STD_LOGIC;
    signal read_k_v_6_U0_start_write : STD_LOGIC;
    signal read_attn_U0_ap_start : STD_LOGIC;
    signal read_attn_U0_ap_done : STD_LOGIC;
    signal read_attn_U0_ap_continue : STD_LOGIC;
    signal read_attn_U0_ap_idle : STD_LOGIC;
    signal read_attn_U0_ap_ready : STD_LOGIC;
    signal read_attn_U0_m_axi_inout1_AWVALID : STD_LOGIC;
    signal read_attn_U0_m_axi_inout1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_attn_U0_m_axi_inout1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_U0_m_axi_inout1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_attn_U0_m_axi_inout1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_U0_m_axi_inout1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_U0_m_axi_inout1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_U0_m_axi_inout1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_U0_m_axi_inout1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_U0_m_axi_inout1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_U0_m_axi_inout1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_U0_m_axi_inout1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_U0_m_axi_inout1_WVALID : STD_LOGIC;
    signal read_attn_U0_m_axi_inout1_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal read_attn_U0_m_axi_inout1_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal read_attn_U0_m_axi_inout1_WLAST : STD_LOGIC;
    signal read_attn_U0_m_axi_inout1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_U0_m_axi_inout1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_U0_m_axi_inout1_ARVALID : STD_LOGIC;
    signal read_attn_U0_m_axi_inout1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_attn_U0_m_axi_inout1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_U0_m_axi_inout1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_attn_U0_m_axi_inout1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_U0_m_axi_inout1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_U0_m_axi_inout1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_U0_m_axi_inout1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_U0_m_axi_inout1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_U0_m_axi_inout1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_U0_m_axi_inout1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_U0_m_axi_inout1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_U0_m_axi_inout1_RREADY : STD_LOGIC;
    signal read_attn_U0_m_axi_inout1_BREADY : STD_LOGIC;
    signal read_attn_U0_attn_stream_din : STD_LOGIC_VECTOR (127 downto 0);
    signal read_attn_U0_attn_stream_write : STD_LOGIC;
    signal read_attn_U0_start_out : STD_LOGIC;
    signal read_attn_U0_start_write : STD_LOGIC;
    signal read_attn_softmax_info_U0_ap_start : STD_LOGIC;
    signal read_attn_softmax_info_U0_ap_done : STD_LOGIC;
    signal read_attn_softmax_info_U0_ap_continue : STD_LOGIC;
    signal read_attn_softmax_info_U0_ap_idle : STD_LOGIC;
    signal read_attn_softmax_info_U0_ap_ready : STD_LOGIC;
    signal read_attn_softmax_info_U0_attn_softmax_info_stream_din : STD_LOGIC_VECTOR (255 downto 0);
    signal read_attn_softmax_info_U0_attn_softmax_info_stream_write : STD_LOGIC;
    signal read_attn_softmax_info_U0_m_axi_inout4_AWVALID : STD_LOGIC;
    signal read_attn_softmax_info_U0_m_axi_inout4_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_WVALID : STD_LOGIC;
    signal read_attn_softmax_info_U0_m_axi_inout4_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_WLAST : STD_LOGIC;
    signal read_attn_softmax_info_U0_m_axi_inout4_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARVALID : STD_LOGIC;
    signal read_attn_softmax_info_U0_m_axi_inout4_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_attn_softmax_info_U0_m_axi_inout4_RREADY : STD_LOGIC;
    signal read_attn_softmax_info_U0_m_axi_inout4_BREADY : STD_LOGIC;
    signal prepare_attn_U0_ap_start : STD_LOGIC;
    signal prepare_attn_U0_ap_done : STD_LOGIC;
    signal prepare_attn_U0_ap_continue : STD_LOGIC;
    signal prepare_attn_U0_ap_idle : STD_LOGIC;
    signal prepare_attn_U0_ap_ready : STD_LOGIC;
    signal prepare_attn_U0_attn_stream_read : STD_LOGIC;
    signal prepare_attn_U0_qxk_out_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal prepare_attn_U0_qxk_out_stream_write : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_ap_start : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_ap_done : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_ap_continue : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_ap_idle : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_ap_ready : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_attn_softmax_info_stream_read : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_qxk_out_stream_read : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_v_stream_read : STD_LOGIC;
    signal compute_attn_matmul_v_7_U0_attn_matmul_v_stream_din : STD_LOGIC_VECTOR (255 downto 0);
    signal compute_attn_matmul_v_7_U0_attn_matmul_v_stream_write : STD_LOGIC;
    signal write_attn_matmul_v_U0_ap_start : STD_LOGIC;
    signal write_attn_matmul_v_U0_ap_done : STD_LOGIC;
    signal write_attn_matmul_v_U0_ap_continue : STD_LOGIC;
    signal write_attn_matmul_v_U0_ap_idle : STD_LOGIC;
    signal write_attn_matmul_v_U0_ap_ready : STD_LOGIC;
    signal write_attn_matmul_v_U0_m_axi_inout1_AWVALID : STD_LOGIC;
    signal write_attn_matmul_v_U0_m_axi_inout1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_WVALID : STD_LOGIC;
    signal write_attn_matmul_v_U0_m_axi_inout1_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_WLAST : STD_LOGIC;
    signal write_attn_matmul_v_U0_m_axi_inout1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARVALID : STD_LOGIC;
    signal write_attn_matmul_v_U0_m_axi_inout1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_attn_matmul_v_U0_m_axi_inout1_RREADY : STD_LOGIC;
    signal write_attn_matmul_v_U0_m_axi_inout1_BREADY : STD_LOGIC;
    signal write_attn_matmul_v_U0_attn_matmul_v_read : STD_LOGIC;
    signal write_attn_matmul_v_U0_attn_matmul_v_stream_read : STD_LOGIC;
    signal attn_matmul_v_c_full_n : STD_LOGIC;
    signal attn_matmul_v_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal attn_matmul_v_c_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal attn_matmul_v_c_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal attn_matmul_v_c_empty_n : STD_LOGIC;
    signal v_stream_full_n : STD_LOGIC;
    signal v_stream_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal v_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal v_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal v_stream_empty_n : STD_LOGIC;
    signal attn_stream_full_n : STD_LOGIC;
    signal attn_stream_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal attn_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal attn_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal attn_stream_empty_n : STD_LOGIC;
    signal attn_softmax_info_stream_full_n : STD_LOGIC;
    signal attn_softmax_info_stream_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal attn_softmax_info_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal attn_softmax_info_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal attn_softmax_info_stream_empty_n : STD_LOGIC;
    signal qxk_out_stream_full_n : STD_LOGIC;
    signal qxk_out_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal qxk_out_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal qxk_out_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal qxk_out_stream_empty_n : STD_LOGIC;
    signal attn_matmul_v_stream_full_n : STD_LOGIC;
    signal attn_matmul_v_stream_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal attn_matmul_v_stream_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal attn_matmul_v_stream_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal attn_matmul_v_stream_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc25_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc25_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_k_v_6_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_k_v_6_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_attn_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_attn_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_attn_softmax_info_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_attn_softmax_info_U0_ap_ready : STD_LOGIC;
    signal start_for_write_attn_matmul_v_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_write_attn_matmul_v_U0_full_n : STD_LOGIC;
    signal start_for_write_attn_matmul_v_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_write_attn_matmul_v_U0_empty_n : STD_LOGIC;
    signal start_for_compute_attn_matmul_v_7_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_attn_matmul_v_7_U0_full_n : STD_LOGIC;
    signal start_for_compute_attn_matmul_v_7_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_attn_matmul_v_7_U0_empty_n : STD_LOGIC;
    signal start_for_prepare_attn_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_prepare_attn_U0_full_n : STD_LOGIC;
    signal start_for_prepare_attn_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_prepare_attn_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_act_entry_proc25 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        attn_matmul_v : IN STD_LOGIC_VECTOR (63 downto 0);
        attn_matmul_v_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        attn_matmul_v_c_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        attn_matmul_v_c_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        attn_matmul_v_c_full_n : IN STD_LOGIC;
        attn_matmul_v_c_write : OUT STD_LOGIC );
    end component;


    component ViT_act_read_k_v_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_inout2_AWVALID : OUT STD_LOGIC;
        m_axi_inout2_AWREADY : IN STD_LOGIC;
        m_axi_inout2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_WVALID : OUT STD_LOGIC;
        m_axi_inout2_WREADY : IN STD_LOGIC;
        m_axi_inout2_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout2_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout2_WLAST : OUT STD_LOGIC;
        m_axi_inout2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_ARVALID : OUT STD_LOGIC;
        m_axi_inout2_ARREADY : IN STD_LOGIC;
        m_axi_inout2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_RVALID : IN STD_LOGIC;
        m_axi_inout2_RREADY : OUT STD_LOGIC;
        m_axi_inout2_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout2_RLAST : IN STD_LOGIC;
        m_axi_inout2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_inout2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout2_BVALID : IN STD_LOGIC;
        m_axi_inout2_BREADY : OUT STD_LOGIC;
        m_axi_inout2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        v_stream_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        v_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        v_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        v_stream_full_n : IN STD_LOGIC;
        v_stream_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        k : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ViT_act_read_attn IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_inout1_AWVALID : OUT STD_LOGIC;
        m_axi_inout1_AWREADY : IN STD_LOGIC;
        m_axi_inout1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_WVALID : OUT STD_LOGIC;
        m_axi_inout1_WREADY : IN STD_LOGIC;
        m_axi_inout1_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout1_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout1_WLAST : OUT STD_LOGIC;
        m_axi_inout1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_ARVALID : OUT STD_LOGIC;
        m_axi_inout1_ARREADY : IN STD_LOGIC;
        m_axi_inout1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_RVALID : IN STD_LOGIC;
        m_axi_inout1_RREADY : OUT STD_LOGIC;
        m_axi_inout1_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout1_RLAST : IN STD_LOGIC;
        m_axi_inout1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_inout1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_BVALID : IN STD_LOGIC;
        m_axi_inout1_BREADY : OUT STD_LOGIC;
        m_axi_inout1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        attn_stream_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        attn_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_stream_full_n : IN STD_LOGIC;
        attn_stream_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        attn : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ViT_act_read_attn_softmax_info IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        attn_softmax_info_stream_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        attn_softmax_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_softmax_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_softmax_info_stream_full_n : IN STD_LOGIC;
        attn_softmax_info_stream_write : OUT STD_LOGIC;
        m_axi_inout4_AWVALID : OUT STD_LOGIC;
        m_axi_inout4_AWREADY : IN STD_LOGIC;
        m_axi_inout4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_WVALID : OUT STD_LOGIC;
        m_axi_inout4_WREADY : IN STD_LOGIC;
        m_axi_inout4_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout4_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout4_WLAST : OUT STD_LOGIC;
        m_axi_inout4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_ARVALID : OUT STD_LOGIC;
        m_axi_inout4_ARREADY : IN STD_LOGIC;
        m_axi_inout4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_RVALID : IN STD_LOGIC;
        m_axi_inout4_RREADY : OUT STD_LOGIC;
        m_axi_inout4_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout4_RLAST : IN STD_LOGIC;
        m_axi_inout4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_inout4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_BVALID : IN STD_LOGIC;
        m_axi_inout4_BREADY : OUT STD_LOGIC;
        m_axi_inout4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        attn_softmax_info : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ViT_act_prepare_attn IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        attn_stream_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        attn_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_stream_empty_n : IN STD_LOGIC;
        attn_stream_read : OUT STD_LOGIC;
        qxk_out_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        qxk_out_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        qxk_out_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        qxk_out_stream_full_n : IN STD_LOGIC;
        qxk_out_stream_write : OUT STD_LOGIC );
    end component;


    component ViT_act_compute_attn_matmul_v_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        attn_softmax_info_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        attn_softmax_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_softmax_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_softmax_info_stream_empty_n : IN STD_LOGIC;
        attn_softmax_info_stream_read : OUT STD_LOGIC;
        qxk_out_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        qxk_out_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        qxk_out_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        qxk_out_stream_empty_n : IN STD_LOGIC;
        qxk_out_stream_read : OUT STD_LOGIC;
        v_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        v_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        v_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        v_stream_empty_n : IN STD_LOGIC;
        v_stream_read : OUT STD_LOGIC;
        attn_matmul_v_stream_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        attn_matmul_v_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_matmul_v_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_matmul_v_stream_full_n : IN STD_LOGIC;
        attn_matmul_v_stream_write : OUT STD_LOGIC );
    end component;


    component ViT_act_write_attn_matmul_v IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_inout1_AWVALID : OUT STD_LOGIC;
        m_axi_inout1_AWREADY : IN STD_LOGIC;
        m_axi_inout1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_WVALID : OUT STD_LOGIC;
        m_axi_inout1_WREADY : IN STD_LOGIC;
        m_axi_inout1_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout1_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout1_WLAST : OUT STD_LOGIC;
        m_axi_inout1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_ARVALID : OUT STD_LOGIC;
        m_axi_inout1_ARREADY : IN STD_LOGIC;
        m_axi_inout1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_RVALID : IN STD_LOGIC;
        m_axi_inout1_RREADY : OUT STD_LOGIC;
        m_axi_inout1_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout1_RLAST : IN STD_LOGIC;
        m_axi_inout1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_inout1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_BVALID : IN STD_LOGIC;
        m_axi_inout1_BREADY : OUT STD_LOGIC;
        m_axi_inout1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        attn_matmul_v_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        attn_matmul_v_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        attn_matmul_v_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        attn_matmul_v_empty_n : IN STD_LOGIC;
        attn_matmul_v_read : OUT STD_LOGIC;
        attn_matmul_v_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        attn_matmul_v_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_matmul_v_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_matmul_v_stream_empty_n : IN STD_LOGIC;
        attn_matmul_v_stream_read : OUT STD_LOGIC );
    end component;


    component ViT_act_fifo_w64_d5_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (3 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (3 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_act_fifo_w256_d2_S_x0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_act_fifo_w128_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_act_fifo_w512_d2_S_x0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (511 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (511 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_act_start_for_write_attn_matmul_v_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_act_start_for_compute_attn_matmul_v_7_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_act_start_for_prepare_attn_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc25_U0 : component ViT_act_entry_proc25
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc25_U0_ap_start,
        start_full_n => start_for_write_attn_matmul_v_U0_full_n,
        ap_done => entry_proc25_U0_ap_done,
        ap_continue => entry_proc25_U0_ap_continue,
        ap_idle => entry_proc25_U0_ap_idle,
        ap_ready => entry_proc25_U0_ap_ready,
        start_out => entry_proc25_U0_start_out,
        start_write => entry_proc25_U0_start_write,
        attn_matmul_v => attn_matmul_v,
        attn_matmul_v_c_din => entry_proc25_U0_attn_matmul_v_c_din,
        attn_matmul_v_c_num_data_valid => attn_matmul_v_c_num_data_valid,
        attn_matmul_v_c_fifo_cap => attn_matmul_v_c_fifo_cap,
        attn_matmul_v_c_full_n => attn_matmul_v_c_full_n,
        attn_matmul_v_c_write => entry_proc25_U0_attn_matmul_v_c_write);

    read_k_v_6_U0 : component ViT_act_read_k_v_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_k_v_6_U0_ap_start,
        start_full_n => start_for_compute_attn_matmul_v_7_U0_full_n,
        ap_done => read_k_v_6_U0_ap_done,
        ap_continue => read_k_v_6_U0_ap_continue,
        ap_idle => read_k_v_6_U0_ap_idle,
        ap_ready => read_k_v_6_U0_ap_ready,
        m_axi_inout2_AWVALID => read_k_v_6_U0_m_axi_inout2_AWVALID,
        m_axi_inout2_AWREADY => ap_const_logic_0,
        m_axi_inout2_AWADDR => read_k_v_6_U0_m_axi_inout2_AWADDR,
        m_axi_inout2_AWID => read_k_v_6_U0_m_axi_inout2_AWID,
        m_axi_inout2_AWLEN => read_k_v_6_U0_m_axi_inout2_AWLEN,
        m_axi_inout2_AWSIZE => read_k_v_6_U0_m_axi_inout2_AWSIZE,
        m_axi_inout2_AWBURST => read_k_v_6_U0_m_axi_inout2_AWBURST,
        m_axi_inout2_AWLOCK => read_k_v_6_U0_m_axi_inout2_AWLOCK,
        m_axi_inout2_AWCACHE => read_k_v_6_U0_m_axi_inout2_AWCACHE,
        m_axi_inout2_AWPROT => read_k_v_6_U0_m_axi_inout2_AWPROT,
        m_axi_inout2_AWQOS => read_k_v_6_U0_m_axi_inout2_AWQOS,
        m_axi_inout2_AWREGION => read_k_v_6_U0_m_axi_inout2_AWREGION,
        m_axi_inout2_AWUSER => read_k_v_6_U0_m_axi_inout2_AWUSER,
        m_axi_inout2_WVALID => read_k_v_6_U0_m_axi_inout2_WVALID,
        m_axi_inout2_WREADY => ap_const_logic_0,
        m_axi_inout2_WDATA => read_k_v_6_U0_m_axi_inout2_WDATA,
        m_axi_inout2_WSTRB => read_k_v_6_U0_m_axi_inout2_WSTRB,
        m_axi_inout2_WLAST => read_k_v_6_U0_m_axi_inout2_WLAST,
        m_axi_inout2_WID => read_k_v_6_U0_m_axi_inout2_WID,
        m_axi_inout2_WUSER => read_k_v_6_U0_m_axi_inout2_WUSER,
        m_axi_inout2_ARVALID => read_k_v_6_U0_m_axi_inout2_ARVALID,
        m_axi_inout2_ARREADY => m_axi_inout2_ARREADY,
        m_axi_inout2_ARADDR => read_k_v_6_U0_m_axi_inout2_ARADDR,
        m_axi_inout2_ARID => read_k_v_6_U0_m_axi_inout2_ARID,
        m_axi_inout2_ARLEN => read_k_v_6_U0_m_axi_inout2_ARLEN,
        m_axi_inout2_ARSIZE => read_k_v_6_U0_m_axi_inout2_ARSIZE,
        m_axi_inout2_ARBURST => read_k_v_6_U0_m_axi_inout2_ARBURST,
        m_axi_inout2_ARLOCK => read_k_v_6_U0_m_axi_inout2_ARLOCK,
        m_axi_inout2_ARCACHE => read_k_v_6_U0_m_axi_inout2_ARCACHE,
        m_axi_inout2_ARPROT => read_k_v_6_U0_m_axi_inout2_ARPROT,
        m_axi_inout2_ARQOS => read_k_v_6_U0_m_axi_inout2_ARQOS,
        m_axi_inout2_ARREGION => read_k_v_6_U0_m_axi_inout2_ARREGION,
        m_axi_inout2_ARUSER => read_k_v_6_U0_m_axi_inout2_ARUSER,
        m_axi_inout2_RVALID => m_axi_inout2_RVALID,
        m_axi_inout2_RREADY => read_k_v_6_U0_m_axi_inout2_RREADY,
        m_axi_inout2_RDATA => m_axi_inout2_RDATA,
        m_axi_inout2_RLAST => m_axi_inout2_RLAST,
        m_axi_inout2_RID => m_axi_inout2_RID,
        m_axi_inout2_RFIFONUM => m_axi_inout2_RFIFONUM,
        m_axi_inout2_RUSER => m_axi_inout2_RUSER,
        m_axi_inout2_RRESP => m_axi_inout2_RRESP,
        m_axi_inout2_BVALID => ap_const_logic_0,
        m_axi_inout2_BREADY => read_k_v_6_U0_m_axi_inout2_BREADY,
        m_axi_inout2_BRESP => ap_const_lv2_0,
        m_axi_inout2_BID => ap_const_lv1_0,
        m_axi_inout2_BUSER => ap_const_lv1_0,
        v_stream_din => read_k_v_6_U0_v_stream_din,
        v_stream_num_data_valid => v_stream_num_data_valid,
        v_stream_fifo_cap => v_stream_fifo_cap,
        v_stream_full_n => v_stream_full_n,
        v_stream_write => read_k_v_6_U0_v_stream_write,
        start_out => read_k_v_6_U0_start_out,
        start_write => read_k_v_6_U0_start_write,
        k => v);

    read_attn_U0 : component ViT_act_read_attn
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_attn_U0_ap_start,
        start_full_n => start_for_prepare_attn_U0_full_n,
        ap_done => read_attn_U0_ap_done,
        ap_continue => read_attn_U0_ap_continue,
        ap_idle => read_attn_U0_ap_idle,
        ap_ready => read_attn_U0_ap_ready,
        m_axi_inout1_AWVALID => read_attn_U0_m_axi_inout1_AWVALID,
        m_axi_inout1_AWREADY => ap_const_logic_0,
        m_axi_inout1_AWADDR => read_attn_U0_m_axi_inout1_AWADDR,
        m_axi_inout1_AWID => read_attn_U0_m_axi_inout1_AWID,
        m_axi_inout1_AWLEN => read_attn_U0_m_axi_inout1_AWLEN,
        m_axi_inout1_AWSIZE => read_attn_U0_m_axi_inout1_AWSIZE,
        m_axi_inout1_AWBURST => read_attn_U0_m_axi_inout1_AWBURST,
        m_axi_inout1_AWLOCK => read_attn_U0_m_axi_inout1_AWLOCK,
        m_axi_inout1_AWCACHE => read_attn_U0_m_axi_inout1_AWCACHE,
        m_axi_inout1_AWPROT => read_attn_U0_m_axi_inout1_AWPROT,
        m_axi_inout1_AWQOS => read_attn_U0_m_axi_inout1_AWQOS,
        m_axi_inout1_AWREGION => read_attn_U0_m_axi_inout1_AWREGION,
        m_axi_inout1_AWUSER => read_attn_U0_m_axi_inout1_AWUSER,
        m_axi_inout1_WVALID => read_attn_U0_m_axi_inout1_WVALID,
        m_axi_inout1_WREADY => ap_const_logic_0,
        m_axi_inout1_WDATA => read_attn_U0_m_axi_inout1_WDATA,
        m_axi_inout1_WSTRB => read_attn_U0_m_axi_inout1_WSTRB,
        m_axi_inout1_WLAST => read_attn_U0_m_axi_inout1_WLAST,
        m_axi_inout1_WID => read_attn_U0_m_axi_inout1_WID,
        m_axi_inout1_WUSER => read_attn_U0_m_axi_inout1_WUSER,
        m_axi_inout1_ARVALID => read_attn_U0_m_axi_inout1_ARVALID,
        m_axi_inout1_ARREADY => m_axi_inout1_ARREADY,
        m_axi_inout1_ARADDR => read_attn_U0_m_axi_inout1_ARADDR,
        m_axi_inout1_ARID => read_attn_U0_m_axi_inout1_ARID,
        m_axi_inout1_ARLEN => read_attn_U0_m_axi_inout1_ARLEN,
        m_axi_inout1_ARSIZE => read_attn_U0_m_axi_inout1_ARSIZE,
        m_axi_inout1_ARBURST => read_attn_U0_m_axi_inout1_ARBURST,
        m_axi_inout1_ARLOCK => read_attn_U0_m_axi_inout1_ARLOCK,
        m_axi_inout1_ARCACHE => read_attn_U0_m_axi_inout1_ARCACHE,
        m_axi_inout1_ARPROT => read_attn_U0_m_axi_inout1_ARPROT,
        m_axi_inout1_ARQOS => read_attn_U0_m_axi_inout1_ARQOS,
        m_axi_inout1_ARREGION => read_attn_U0_m_axi_inout1_ARREGION,
        m_axi_inout1_ARUSER => read_attn_U0_m_axi_inout1_ARUSER,
        m_axi_inout1_RVALID => m_axi_inout1_RVALID,
        m_axi_inout1_RREADY => read_attn_U0_m_axi_inout1_RREADY,
        m_axi_inout1_RDATA => m_axi_inout1_RDATA,
        m_axi_inout1_RLAST => m_axi_inout1_RLAST,
        m_axi_inout1_RID => m_axi_inout1_RID,
        m_axi_inout1_RFIFONUM => m_axi_inout1_RFIFONUM,
        m_axi_inout1_RUSER => m_axi_inout1_RUSER,
        m_axi_inout1_RRESP => m_axi_inout1_RRESP,
        m_axi_inout1_BVALID => ap_const_logic_0,
        m_axi_inout1_BREADY => read_attn_U0_m_axi_inout1_BREADY,
        m_axi_inout1_BRESP => ap_const_lv2_0,
        m_axi_inout1_BID => ap_const_lv1_0,
        m_axi_inout1_BUSER => ap_const_lv1_0,
        attn_stream_din => read_attn_U0_attn_stream_din,
        attn_stream_num_data_valid => attn_stream_num_data_valid,
        attn_stream_fifo_cap => attn_stream_fifo_cap,
        attn_stream_full_n => attn_stream_full_n,
        attn_stream_write => read_attn_U0_attn_stream_write,
        start_out => read_attn_U0_start_out,
        start_write => read_attn_U0_start_write,
        attn => attn);

    read_attn_softmax_info_U0 : component ViT_act_read_attn_softmax_info
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_attn_softmax_info_U0_ap_start,
        ap_done => read_attn_softmax_info_U0_ap_done,
        ap_continue => read_attn_softmax_info_U0_ap_continue,
        ap_idle => read_attn_softmax_info_U0_ap_idle,
        ap_ready => read_attn_softmax_info_U0_ap_ready,
        attn_softmax_info_stream_din => read_attn_softmax_info_U0_attn_softmax_info_stream_din,
        attn_softmax_info_stream_num_data_valid => attn_softmax_info_stream_num_data_valid,
        attn_softmax_info_stream_fifo_cap => attn_softmax_info_stream_fifo_cap,
        attn_softmax_info_stream_full_n => attn_softmax_info_stream_full_n,
        attn_softmax_info_stream_write => read_attn_softmax_info_U0_attn_softmax_info_stream_write,
        m_axi_inout4_AWVALID => read_attn_softmax_info_U0_m_axi_inout4_AWVALID,
        m_axi_inout4_AWREADY => ap_const_logic_0,
        m_axi_inout4_AWADDR => read_attn_softmax_info_U0_m_axi_inout4_AWADDR,
        m_axi_inout4_AWID => read_attn_softmax_info_U0_m_axi_inout4_AWID,
        m_axi_inout4_AWLEN => read_attn_softmax_info_U0_m_axi_inout4_AWLEN,
        m_axi_inout4_AWSIZE => read_attn_softmax_info_U0_m_axi_inout4_AWSIZE,
        m_axi_inout4_AWBURST => read_attn_softmax_info_U0_m_axi_inout4_AWBURST,
        m_axi_inout4_AWLOCK => read_attn_softmax_info_U0_m_axi_inout4_AWLOCK,
        m_axi_inout4_AWCACHE => read_attn_softmax_info_U0_m_axi_inout4_AWCACHE,
        m_axi_inout4_AWPROT => read_attn_softmax_info_U0_m_axi_inout4_AWPROT,
        m_axi_inout4_AWQOS => read_attn_softmax_info_U0_m_axi_inout4_AWQOS,
        m_axi_inout4_AWREGION => read_attn_softmax_info_U0_m_axi_inout4_AWREGION,
        m_axi_inout4_AWUSER => read_attn_softmax_info_U0_m_axi_inout4_AWUSER,
        m_axi_inout4_WVALID => read_attn_softmax_info_U0_m_axi_inout4_WVALID,
        m_axi_inout4_WREADY => ap_const_logic_0,
        m_axi_inout4_WDATA => read_attn_softmax_info_U0_m_axi_inout4_WDATA,
        m_axi_inout4_WSTRB => read_attn_softmax_info_U0_m_axi_inout4_WSTRB,
        m_axi_inout4_WLAST => read_attn_softmax_info_U0_m_axi_inout4_WLAST,
        m_axi_inout4_WID => read_attn_softmax_info_U0_m_axi_inout4_WID,
        m_axi_inout4_WUSER => read_attn_softmax_info_U0_m_axi_inout4_WUSER,
        m_axi_inout4_ARVALID => read_attn_softmax_info_U0_m_axi_inout4_ARVALID,
        m_axi_inout4_ARREADY => m_axi_inout4_ARREADY,
        m_axi_inout4_ARADDR => read_attn_softmax_info_U0_m_axi_inout4_ARADDR,
        m_axi_inout4_ARID => read_attn_softmax_info_U0_m_axi_inout4_ARID,
        m_axi_inout4_ARLEN => read_attn_softmax_info_U0_m_axi_inout4_ARLEN,
        m_axi_inout4_ARSIZE => read_attn_softmax_info_U0_m_axi_inout4_ARSIZE,
        m_axi_inout4_ARBURST => read_attn_softmax_info_U0_m_axi_inout4_ARBURST,
        m_axi_inout4_ARLOCK => read_attn_softmax_info_U0_m_axi_inout4_ARLOCK,
        m_axi_inout4_ARCACHE => read_attn_softmax_info_U0_m_axi_inout4_ARCACHE,
        m_axi_inout4_ARPROT => read_attn_softmax_info_U0_m_axi_inout4_ARPROT,
        m_axi_inout4_ARQOS => read_attn_softmax_info_U0_m_axi_inout4_ARQOS,
        m_axi_inout4_ARREGION => read_attn_softmax_info_U0_m_axi_inout4_ARREGION,
        m_axi_inout4_ARUSER => read_attn_softmax_info_U0_m_axi_inout4_ARUSER,
        m_axi_inout4_RVALID => m_axi_inout4_RVALID,
        m_axi_inout4_RREADY => read_attn_softmax_info_U0_m_axi_inout4_RREADY,
        m_axi_inout4_RDATA => m_axi_inout4_RDATA,
        m_axi_inout4_RLAST => m_axi_inout4_RLAST,
        m_axi_inout4_RID => m_axi_inout4_RID,
        m_axi_inout4_RFIFONUM => m_axi_inout4_RFIFONUM,
        m_axi_inout4_RUSER => m_axi_inout4_RUSER,
        m_axi_inout4_RRESP => m_axi_inout4_RRESP,
        m_axi_inout4_BVALID => ap_const_logic_0,
        m_axi_inout4_BREADY => read_attn_softmax_info_U0_m_axi_inout4_BREADY,
        m_axi_inout4_BRESP => ap_const_lv2_0,
        m_axi_inout4_BID => ap_const_lv1_0,
        m_axi_inout4_BUSER => ap_const_lv1_0,
        attn_softmax_info => attn_softmax_info);

    prepare_attn_U0 : component ViT_act_prepare_attn
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => prepare_attn_U0_ap_start,
        ap_done => prepare_attn_U0_ap_done,
        ap_continue => prepare_attn_U0_ap_continue,
        ap_idle => prepare_attn_U0_ap_idle,
        ap_ready => prepare_attn_U0_ap_ready,
        attn_stream_dout => attn_stream_dout,
        attn_stream_num_data_valid => attn_stream_num_data_valid,
        attn_stream_fifo_cap => attn_stream_fifo_cap,
        attn_stream_empty_n => attn_stream_empty_n,
        attn_stream_read => prepare_attn_U0_attn_stream_read,
        qxk_out_stream_din => prepare_attn_U0_qxk_out_stream_din,
        qxk_out_stream_num_data_valid => qxk_out_stream_num_data_valid,
        qxk_out_stream_fifo_cap => qxk_out_stream_fifo_cap,
        qxk_out_stream_full_n => qxk_out_stream_full_n,
        qxk_out_stream_write => prepare_attn_U0_qxk_out_stream_write);

    compute_attn_matmul_v_7_U0 : component ViT_act_compute_attn_matmul_v_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_attn_matmul_v_7_U0_ap_start,
        ap_done => compute_attn_matmul_v_7_U0_ap_done,
        ap_continue => compute_attn_matmul_v_7_U0_ap_continue,
        ap_idle => compute_attn_matmul_v_7_U0_ap_idle,
        ap_ready => compute_attn_matmul_v_7_U0_ap_ready,
        attn_softmax_info_stream_dout => attn_softmax_info_stream_dout,
        attn_softmax_info_stream_num_data_valid => attn_softmax_info_stream_num_data_valid,
        attn_softmax_info_stream_fifo_cap => attn_softmax_info_stream_fifo_cap,
        attn_softmax_info_stream_empty_n => attn_softmax_info_stream_empty_n,
        attn_softmax_info_stream_read => compute_attn_matmul_v_7_U0_attn_softmax_info_stream_read,
        qxk_out_stream_dout => qxk_out_stream_dout,
        qxk_out_stream_num_data_valid => qxk_out_stream_num_data_valid,
        qxk_out_stream_fifo_cap => qxk_out_stream_fifo_cap,
        qxk_out_stream_empty_n => qxk_out_stream_empty_n,
        qxk_out_stream_read => compute_attn_matmul_v_7_U0_qxk_out_stream_read,
        v_stream_dout => v_stream_dout,
        v_stream_num_data_valid => v_stream_num_data_valid,
        v_stream_fifo_cap => v_stream_fifo_cap,
        v_stream_empty_n => v_stream_empty_n,
        v_stream_read => compute_attn_matmul_v_7_U0_v_stream_read,
        attn_matmul_v_stream_din => compute_attn_matmul_v_7_U0_attn_matmul_v_stream_din,
        attn_matmul_v_stream_num_data_valid => attn_matmul_v_stream_num_data_valid,
        attn_matmul_v_stream_fifo_cap => attn_matmul_v_stream_fifo_cap,
        attn_matmul_v_stream_full_n => attn_matmul_v_stream_full_n,
        attn_matmul_v_stream_write => compute_attn_matmul_v_7_U0_attn_matmul_v_stream_write);

    write_attn_matmul_v_U0 : component ViT_act_write_attn_matmul_v
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => write_attn_matmul_v_U0_ap_start,
        ap_done => write_attn_matmul_v_U0_ap_done,
        ap_continue => write_attn_matmul_v_U0_ap_continue,
        ap_idle => write_attn_matmul_v_U0_ap_idle,
        ap_ready => write_attn_matmul_v_U0_ap_ready,
        m_axi_inout1_AWVALID => write_attn_matmul_v_U0_m_axi_inout1_AWVALID,
        m_axi_inout1_AWREADY => m_axi_inout1_AWREADY,
        m_axi_inout1_AWADDR => write_attn_matmul_v_U0_m_axi_inout1_AWADDR,
        m_axi_inout1_AWID => write_attn_matmul_v_U0_m_axi_inout1_AWID,
        m_axi_inout1_AWLEN => write_attn_matmul_v_U0_m_axi_inout1_AWLEN,
        m_axi_inout1_AWSIZE => write_attn_matmul_v_U0_m_axi_inout1_AWSIZE,
        m_axi_inout1_AWBURST => write_attn_matmul_v_U0_m_axi_inout1_AWBURST,
        m_axi_inout1_AWLOCK => write_attn_matmul_v_U0_m_axi_inout1_AWLOCK,
        m_axi_inout1_AWCACHE => write_attn_matmul_v_U0_m_axi_inout1_AWCACHE,
        m_axi_inout1_AWPROT => write_attn_matmul_v_U0_m_axi_inout1_AWPROT,
        m_axi_inout1_AWQOS => write_attn_matmul_v_U0_m_axi_inout1_AWQOS,
        m_axi_inout1_AWREGION => write_attn_matmul_v_U0_m_axi_inout1_AWREGION,
        m_axi_inout1_AWUSER => write_attn_matmul_v_U0_m_axi_inout1_AWUSER,
        m_axi_inout1_WVALID => write_attn_matmul_v_U0_m_axi_inout1_WVALID,
        m_axi_inout1_WREADY => m_axi_inout1_WREADY,
        m_axi_inout1_WDATA => write_attn_matmul_v_U0_m_axi_inout1_WDATA,
        m_axi_inout1_WSTRB => write_attn_matmul_v_U0_m_axi_inout1_WSTRB,
        m_axi_inout1_WLAST => write_attn_matmul_v_U0_m_axi_inout1_WLAST,
        m_axi_inout1_WID => write_attn_matmul_v_U0_m_axi_inout1_WID,
        m_axi_inout1_WUSER => write_attn_matmul_v_U0_m_axi_inout1_WUSER,
        m_axi_inout1_ARVALID => write_attn_matmul_v_U0_m_axi_inout1_ARVALID,
        m_axi_inout1_ARREADY => ap_const_logic_0,
        m_axi_inout1_ARADDR => write_attn_matmul_v_U0_m_axi_inout1_ARADDR,
        m_axi_inout1_ARID => write_attn_matmul_v_U0_m_axi_inout1_ARID,
        m_axi_inout1_ARLEN => write_attn_matmul_v_U0_m_axi_inout1_ARLEN,
        m_axi_inout1_ARSIZE => write_attn_matmul_v_U0_m_axi_inout1_ARSIZE,
        m_axi_inout1_ARBURST => write_attn_matmul_v_U0_m_axi_inout1_ARBURST,
        m_axi_inout1_ARLOCK => write_attn_matmul_v_U0_m_axi_inout1_ARLOCK,
        m_axi_inout1_ARCACHE => write_attn_matmul_v_U0_m_axi_inout1_ARCACHE,
        m_axi_inout1_ARPROT => write_attn_matmul_v_U0_m_axi_inout1_ARPROT,
        m_axi_inout1_ARQOS => write_attn_matmul_v_U0_m_axi_inout1_ARQOS,
        m_axi_inout1_ARREGION => write_attn_matmul_v_U0_m_axi_inout1_ARREGION,
        m_axi_inout1_ARUSER => write_attn_matmul_v_U0_m_axi_inout1_ARUSER,
        m_axi_inout1_RVALID => ap_const_logic_0,
        m_axi_inout1_RREADY => write_attn_matmul_v_U0_m_axi_inout1_RREADY,
        m_axi_inout1_RDATA => ap_const_lv256_lc_1,
        m_axi_inout1_RLAST => ap_const_logic_0,
        m_axi_inout1_RID => ap_const_lv1_0,
        m_axi_inout1_RFIFONUM => ap_const_lv9_0,
        m_axi_inout1_RUSER => ap_const_lv1_0,
        m_axi_inout1_RRESP => ap_const_lv2_0,
        m_axi_inout1_BVALID => m_axi_inout1_BVALID,
        m_axi_inout1_BREADY => write_attn_matmul_v_U0_m_axi_inout1_BREADY,
        m_axi_inout1_BRESP => m_axi_inout1_BRESP,
        m_axi_inout1_BID => m_axi_inout1_BID,
        m_axi_inout1_BUSER => m_axi_inout1_BUSER,
        attn_matmul_v_dout => attn_matmul_v_c_dout,
        attn_matmul_v_num_data_valid => attn_matmul_v_c_num_data_valid,
        attn_matmul_v_fifo_cap => attn_matmul_v_c_fifo_cap,
        attn_matmul_v_empty_n => attn_matmul_v_c_empty_n,
        attn_matmul_v_read => write_attn_matmul_v_U0_attn_matmul_v_read,
        attn_matmul_v_stream_dout => attn_matmul_v_stream_dout,
        attn_matmul_v_stream_num_data_valid => attn_matmul_v_stream_num_data_valid,
        attn_matmul_v_stream_fifo_cap => attn_matmul_v_stream_fifo_cap,
        attn_matmul_v_stream_empty_n => attn_matmul_v_stream_empty_n,
        attn_matmul_v_stream_read => write_attn_matmul_v_U0_attn_matmul_v_stream_read);

    attn_matmul_v_c_U : component ViT_act_fifo_w64_d5_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc25_U0_attn_matmul_v_c_din,
        if_full_n => attn_matmul_v_c_full_n,
        if_write => entry_proc25_U0_attn_matmul_v_c_write,
        if_dout => attn_matmul_v_c_dout,
        if_num_data_valid => attn_matmul_v_c_num_data_valid,
        if_fifo_cap => attn_matmul_v_c_fifo_cap,
        if_empty_n => attn_matmul_v_c_empty_n,
        if_read => write_attn_matmul_v_U0_attn_matmul_v_read);

    v_stream_U : component ViT_act_fifo_w256_d2_S_x0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_k_v_6_U0_v_stream_din,
        if_full_n => v_stream_full_n,
        if_write => read_k_v_6_U0_v_stream_write,
        if_dout => v_stream_dout,
        if_num_data_valid => v_stream_num_data_valid,
        if_fifo_cap => v_stream_fifo_cap,
        if_empty_n => v_stream_empty_n,
        if_read => compute_attn_matmul_v_7_U0_v_stream_read);

    attn_stream_U : component ViT_act_fifo_w128_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_attn_U0_attn_stream_din,
        if_full_n => attn_stream_full_n,
        if_write => read_attn_U0_attn_stream_write,
        if_dout => attn_stream_dout,
        if_num_data_valid => attn_stream_num_data_valid,
        if_fifo_cap => attn_stream_fifo_cap,
        if_empty_n => attn_stream_empty_n,
        if_read => prepare_attn_U0_attn_stream_read);

    attn_softmax_info_stream_U : component ViT_act_fifo_w256_d2_S_x0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_attn_softmax_info_U0_attn_softmax_info_stream_din,
        if_full_n => attn_softmax_info_stream_full_n,
        if_write => read_attn_softmax_info_U0_attn_softmax_info_stream_write,
        if_dout => attn_softmax_info_stream_dout,
        if_num_data_valid => attn_softmax_info_stream_num_data_valid,
        if_fifo_cap => attn_softmax_info_stream_fifo_cap,
        if_empty_n => attn_softmax_info_stream_empty_n,
        if_read => compute_attn_matmul_v_7_U0_attn_softmax_info_stream_read);

    qxk_out_stream_U : component ViT_act_fifo_w512_d2_S_x0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => prepare_attn_U0_qxk_out_stream_din,
        if_full_n => qxk_out_stream_full_n,
        if_write => prepare_attn_U0_qxk_out_stream_write,
        if_dout => qxk_out_stream_dout,
        if_num_data_valid => qxk_out_stream_num_data_valid,
        if_fifo_cap => qxk_out_stream_fifo_cap,
        if_empty_n => qxk_out_stream_empty_n,
        if_read => compute_attn_matmul_v_7_U0_qxk_out_stream_read);

    attn_matmul_v_stream_U : component ViT_act_fifo_w256_d2_S_x0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_attn_matmul_v_7_U0_attn_matmul_v_stream_din,
        if_full_n => attn_matmul_v_stream_full_n,
        if_write => compute_attn_matmul_v_7_U0_attn_matmul_v_stream_write,
        if_dout => attn_matmul_v_stream_dout,
        if_num_data_valid => attn_matmul_v_stream_num_data_valid,
        if_fifo_cap => attn_matmul_v_stream_fifo_cap,
        if_empty_n => attn_matmul_v_stream_empty_n,
        if_read => write_attn_matmul_v_U0_attn_matmul_v_stream_read);

    start_for_write_attn_matmul_v_U0_U : component ViT_act_start_for_write_attn_matmul_v_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_write_attn_matmul_v_U0_din,
        if_full_n => start_for_write_attn_matmul_v_U0_full_n,
        if_write => entry_proc25_U0_start_write,
        if_dout => start_for_write_attn_matmul_v_U0_dout,
        if_empty_n => start_for_write_attn_matmul_v_U0_empty_n,
        if_read => write_attn_matmul_v_U0_ap_ready);

    start_for_compute_attn_matmul_v_7_U0_U : component ViT_act_start_for_compute_attn_matmul_v_7_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_compute_attn_matmul_v_7_U0_din,
        if_full_n => start_for_compute_attn_matmul_v_7_U0_full_n,
        if_write => read_k_v_6_U0_start_write,
        if_dout => start_for_compute_attn_matmul_v_7_U0_dout,
        if_empty_n => start_for_compute_attn_matmul_v_7_U0_empty_n,
        if_read => compute_attn_matmul_v_7_U0_ap_ready);

    start_for_prepare_attn_U0_U : component ViT_act_start_for_prepare_attn_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_prepare_attn_U0_din,
        if_full_n => start_for_prepare_attn_U0_full_n,
        if_write => read_attn_U0_start_write,
        if_dout => start_for_prepare_attn_U0_dout,
        if_empty_n => start_for_prepare_attn_U0_empty_n,
        if_read => prepare_attn_U0_ap_ready);





    ap_sync_reg_entry_proc25_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_entry_proc25_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc25_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc25_U0_ap_ready <= ap_sync_entry_proc25_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_attn_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_attn_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_attn_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_attn_U0_ap_ready <= ap_sync_read_attn_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_attn_softmax_info_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_attn_softmax_info_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_attn_softmax_info_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_attn_softmax_info_U0_ap_ready <= ap_sync_read_attn_softmax_info_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_k_v_6_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_k_v_6_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_k_v_6_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_k_v_6_U0_ap_ready <= ap_sync_read_k_v_6_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= write_attn_matmul_v_U0_ap_done;
    ap_idle <= (write_attn_matmul_v_U0_ap_idle and read_k_v_6_U0_ap_idle and read_attn_softmax_info_U0_ap_idle and read_attn_U0_ap_idle and prepare_attn_U0_ap_idle and entry_proc25_U0_ap_idle and compute_attn_matmul_v_7_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_entry_proc25_U0_ap_ready <= (entry_proc25_U0_ap_ready or ap_sync_reg_entry_proc25_U0_ap_ready);
    ap_sync_read_attn_U0_ap_ready <= (read_attn_U0_ap_ready or ap_sync_reg_read_attn_U0_ap_ready);
    ap_sync_read_attn_softmax_info_U0_ap_ready <= (read_attn_softmax_info_U0_ap_ready or ap_sync_reg_read_attn_softmax_info_U0_ap_ready);
    ap_sync_read_k_v_6_U0_ap_ready <= (read_k_v_6_U0_ap_ready or ap_sync_reg_read_k_v_6_U0_ap_ready);
    ap_sync_ready <= (ap_sync_read_k_v_6_U0_ap_ready and ap_sync_read_attn_softmax_info_U0_ap_ready and ap_sync_read_attn_U0_ap_ready and ap_sync_entry_proc25_U0_ap_ready);
    compute_attn_matmul_v_7_U0_ap_continue <= ap_const_logic_1;
    compute_attn_matmul_v_7_U0_ap_start <= start_for_compute_attn_matmul_v_7_U0_empty_n;
    entry_proc25_U0_ap_continue <= ap_const_logic_1;
    entry_proc25_U0_ap_start <= ((ap_sync_reg_entry_proc25_U0_ap_ready xor ap_const_logic_1) and ap_start);
    m_axi_inout1_ARADDR <= read_attn_U0_m_axi_inout1_ARADDR;
    m_axi_inout1_ARBURST <= read_attn_U0_m_axi_inout1_ARBURST;
    m_axi_inout1_ARCACHE <= read_attn_U0_m_axi_inout1_ARCACHE;
    m_axi_inout1_ARID <= read_attn_U0_m_axi_inout1_ARID;
    m_axi_inout1_ARLEN <= read_attn_U0_m_axi_inout1_ARLEN;
    m_axi_inout1_ARLOCK <= read_attn_U0_m_axi_inout1_ARLOCK;
    m_axi_inout1_ARPROT <= read_attn_U0_m_axi_inout1_ARPROT;
    m_axi_inout1_ARQOS <= read_attn_U0_m_axi_inout1_ARQOS;
    m_axi_inout1_ARREGION <= read_attn_U0_m_axi_inout1_ARREGION;
    m_axi_inout1_ARSIZE <= read_attn_U0_m_axi_inout1_ARSIZE;
    m_axi_inout1_ARUSER <= read_attn_U0_m_axi_inout1_ARUSER;
    m_axi_inout1_ARVALID <= read_attn_U0_m_axi_inout1_ARVALID;
    m_axi_inout1_AWADDR <= write_attn_matmul_v_U0_m_axi_inout1_AWADDR;
    m_axi_inout1_AWBURST <= write_attn_matmul_v_U0_m_axi_inout1_AWBURST;
    m_axi_inout1_AWCACHE <= write_attn_matmul_v_U0_m_axi_inout1_AWCACHE;
    m_axi_inout1_AWID <= write_attn_matmul_v_U0_m_axi_inout1_AWID;
    m_axi_inout1_AWLEN <= write_attn_matmul_v_U0_m_axi_inout1_AWLEN;
    m_axi_inout1_AWLOCK <= write_attn_matmul_v_U0_m_axi_inout1_AWLOCK;
    m_axi_inout1_AWPROT <= write_attn_matmul_v_U0_m_axi_inout1_AWPROT;
    m_axi_inout1_AWQOS <= write_attn_matmul_v_U0_m_axi_inout1_AWQOS;
    m_axi_inout1_AWREGION <= write_attn_matmul_v_U0_m_axi_inout1_AWREGION;
    m_axi_inout1_AWSIZE <= write_attn_matmul_v_U0_m_axi_inout1_AWSIZE;
    m_axi_inout1_AWUSER <= write_attn_matmul_v_U0_m_axi_inout1_AWUSER;
    m_axi_inout1_AWVALID <= write_attn_matmul_v_U0_m_axi_inout1_AWVALID;
    m_axi_inout1_BREADY <= write_attn_matmul_v_U0_m_axi_inout1_BREADY;
    m_axi_inout1_RREADY <= read_attn_U0_m_axi_inout1_RREADY;
    m_axi_inout1_WDATA <= write_attn_matmul_v_U0_m_axi_inout1_WDATA;
    m_axi_inout1_WID <= write_attn_matmul_v_U0_m_axi_inout1_WID;
    m_axi_inout1_WLAST <= write_attn_matmul_v_U0_m_axi_inout1_WLAST;
    m_axi_inout1_WSTRB <= write_attn_matmul_v_U0_m_axi_inout1_WSTRB;
    m_axi_inout1_WUSER <= write_attn_matmul_v_U0_m_axi_inout1_WUSER;
    m_axi_inout1_WVALID <= write_attn_matmul_v_U0_m_axi_inout1_WVALID;
    m_axi_inout2_ARADDR <= read_k_v_6_U0_m_axi_inout2_ARADDR;
    m_axi_inout2_ARBURST <= read_k_v_6_U0_m_axi_inout2_ARBURST;
    m_axi_inout2_ARCACHE <= read_k_v_6_U0_m_axi_inout2_ARCACHE;
    m_axi_inout2_ARID <= read_k_v_6_U0_m_axi_inout2_ARID;
    m_axi_inout2_ARLEN <= read_k_v_6_U0_m_axi_inout2_ARLEN;
    m_axi_inout2_ARLOCK <= read_k_v_6_U0_m_axi_inout2_ARLOCK;
    m_axi_inout2_ARPROT <= read_k_v_6_U0_m_axi_inout2_ARPROT;
    m_axi_inout2_ARQOS <= read_k_v_6_U0_m_axi_inout2_ARQOS;
    m_axi_inout2_ARREGION <= read_k_v_6_U0_m_axi_inout2_ARREGION;
    m_axi_inout2_ARSIZE <= read_k_v_6_U0_m_axi_inout2_ARSIZE;
    m_axi_inout2_ARUSER <= read_k_v_6_U0_m_axi_inout2_ARUSER;
    m_axi_inout2_ARVALID <= read_k_v_6_U0_m_axi_inout2_ARVALID;
    m_axi_inout2_AWADDR <= ap_const_lv64_0;
    m_axi_inout2_AWBURST <= ap_const_lv2_0;
    m_axi_inout2_AWCACHE <= ap_const_lv4_0;
    m_axi_inout2_AWID <= ap_const_lv1_0;
    m_axi_inout2_AWLEN <= ap_const_lv32_0;
    m_axi_inout2_AWLOCK <= ap_const_lv2_0;
    m_axi_inout2_AWPROT <= ap_const_lv3_0;
    m_axi_inout2_AWQOS <= ap_const_lv4_0;
    m_axi_inout2_AWREGION <= ap_const_lv4_0;
    m_axi_inout2_AWSIZE <= ap_const_lv3_0;
    m_axi_inout2_AWUSER <= ap_const_lv1_0;
    m_axi_inout2_AWVALID <= ap_const_logic_0;
    m_axi_inout2_BREADY <= ap_const_logic_0;
    m_axi_inout2_RREADY <= read_k_v_6_U0_m_axi_inout2_RREADY;
    m_axi_inout2_WDATA <= ap_const_lv256_lc_1;
    m_axi_inout2_WID <= ap_const_lv1_0;
    m_axi_inout2_WLAST <= ap_const_logic_0;
    m_axi_inout2_WSTRB <= ap_const_lv32_0;
    m_axi_inout2_WUSER <= ap_const_lv1_0;
    m_axi_inout2_WVALID <= ap_const_logic_0;
    m_axi_inout4_ARADDR <= read_attn_softmax_info_U0_m_axi_inout4_ARADDR;
    m_axi_inout4_ARBURST <= read_attn_softmax_info_U0_m_axi_inout4_ARBURST;
    m_axi_inout4_ARCACHE <= read_attn_softmax_info_U0_m_axi_inout4_ARCACHE;
    m_axi_inout4_ARID <= read_attn_softmax_info_U0_m_axi_inout4_ARID;
    m_axi_inout4_ARLEN <= read_attn_softmax_info_U0_m_axi_inout4_ARLEN;
    m_axi_inout4_ARLOCK <= read_attn_softmax_info_U0_m_axi_inout4_ARLOCK;
    m_axi_inout4_ARPROT <= read_attn_softmax_info_U0_m_axi_inout4_ARPROT;
    m_axi_inout4_ARQOS <= read_attn_softmax_info_U0_m_axi_inout4_ARQOS;
    m_axi_inout4_ARREGION <= read_attn_softmax_info_U0_m_axi_inout4_ARREGION;
    m_axi_inout4_ARSIZE <= read_attn_softmax_info_U0_m_axi_inout4_ARSIZE;
    m_axi_inout4_ARUSER <= read_attn_softmax_info_U0_m_axi_inout4_ARUSER;
    m_axi_inout4_ARVALID <= read_attn_softmax_info_U0_m_axi_inout4_ARVALID;
    m_axi_inout4_AWADDR <= ap_const_lv64_0;
    m_axi_inout4_AWBURST <= ap_const_lv2_0;
    m_axi_inout4_AWCACHE <= ap_const_lv4_0;
    m_axi_inout4_AWID <= ap_const_lv1_0;
    m_axi_inout4_AWLEN <= ap_const_lv32_0;
    m_axi_inout4_AWLOCK <= ap_const_lv2_0;
    m_axi_inout4_AWPROT <= ap_const_lv3_0;
    m_axi_inout4_AWQOS <= ap_const_lv4_0;
    m_axi_inout4_AWREGION <= ap_const_lv4_0;
    m_axi_inout4_AWSIZE <= ap_const_lv3_0;
    m_axi_inout4_AWUSER <= ap_const_lv1_0;
    m_axi_inout4_AWVALID <= ap_const_logic_0;
    m_axi_inout4_BREADY <= ap_const_logic_0;
    m_axi_inout4_RREADY <= read_attn_softmax_info_U0_m_axi_inout4_RREADY;
    m_axi_inout4_WDATA <= ap_const_lv256_lc_1;
    m_axi_inout4_WID <= ap_const_lv1_0;
    m_axi_inout4_WLAST <= ap_const_logic_0;
    m_axi_inout4_WSTRB <= ap_const_lv32_0;
    m_axi_inout4_WUSER <= ap_const_lv1_0;
    m_axi_inout4_WVALID <= ap_const_logic_0;
    prepare_attn_U0_ap_continue <= ap_const_logic_1;
    prepare_attn_U0_ap_start <= start_for_prepare_attn_U0_empty_n;
    read_attn_U0_ap_continue <= ap_const_logic_1;
    read_attn_U0_ap_start <= ((ap_sync_reg_read_attn_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_attn_softmax_info_U0_ap_continue <= ap_const_logic_1;
    read_attn_softmax_info_U0_ap_start <= ((ap_sync_reg_read_attn_softmax_info_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_k_v_6_U0_ap_continue <= ap_const_logic_1;
    read_k_v_6_U0_ap_start <= ((ap_sync_reg_read_k_v_6_U0_ap_ready xor ap_const_logic_1) and ap_start);
    start_for_compute_attn_matmul_v_7_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_prepare_attn_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_write_attn_matmul_v_U0_din <= (0=>ap_const_logic_1, others=>'-');
    write_attn_matmul_v_U0_ap_continue <= ap_continue;
    write_attn_matmul_v_U0_ap_start <= start_for_write_attn_matmul_v_U0_empty_n;
end behav;
