-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_act_read_attn_softmax_info is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    attn_softmax_info_stream_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    attn_softmax_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    attn_softmax_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    attn_softmax_info_stream_full_n : IN STD_LOGIC;
    attn_softmax_info_stream_write : OUT STD_LOGIC;
    m_axi_inout4_AWVALID : OUT STD_LOGIC;
    m_axi_inout4_AWREADY : IN STD_LOGIC;
    m_axi_inout4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_WVALID : OUT STD_LOGIC;
    m_axi_inout4_WREADY : IN STD_LOGIC;
    m_axi_inout4_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout4_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout4_WLAST : OUT STD_LOGIC;
    m_axi_inout4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_ARVALID : OUT STD_LOGIC;
    m_axi_inout4_ARREADY : IN STD_LOGIC;
    m_axi_inout4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_RVALID : IN STD_LOGIC;
    m_axi_inout4_RREADY : OUT STD_LOGIC;
    m_axi_inout4_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout4_RLAST : IN STD_LOGIC;
    m_axi_inout4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_inout4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_BVALID : IN STD_LOGIC;
    m_axi_inout4_BREADY : OUT STD_LOGIC;
    m_axi_inout4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    attn_softmax_info : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of ViT_act_read_attn_softmax_info is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal inout4_blk_n_AR : STD_LOGIC;
    signal trunc_ln_fu_64_p4 : STD_LOGIC_VECTOR (58 downto 0);
    signal trunc_ln_reg_85 : STD_LOGIC_VECTOR (58 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_idle : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_ready : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWVALID : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WVALID : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WLAST : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARVALID : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_RREADY : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_BREADY : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_write : STD_LOGIC;
    signal grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal sext_ln388_fu_74_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_act_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_inout4_AWVALID : OUT STD_LOGIC;
        m_axi_inout4_AWREADY : IN STD_LOGIC;
        m_axi_inout4_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout4_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout4_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_WVALID : OUT STD_LOGIC;
        m_axi_inout4_WREADY : IN STD_LOGIC;
        m_axi_inout4_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout4_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout4_WLAST : OUT STD_LOGIC;
        m_axi_inout4_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_ARVALID : OUT STD_LOGIC;
        m_axi_inout4_ARREADY : IN STD_LOGIC;
        m_axi_inout4_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_inout4_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_inout4_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_inout4_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_inout4_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_RVALID : IN STD_LOGIC;
        m_axi_inout4_RREADY : OUT STD_LOGIC;
        m_axi_inout4_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_inout4_RLAST : IN STD_LOGIC;
        m_axi_inout4_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_inout4_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_BVALID : IN STD_LOGIC;
        m_axi_inout4_BREADY : OUT STD_LOGIC;
        m_axi_inout4_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_inout4_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_inout4_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        attn_softmax_info_stream_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        attn_softmax_info_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_softmax_info_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        attn_softmax_info_stream_full_n : IN STD_LOGIC;
        attn_softmax_info_stream_write : OUT STD_LOGIC;
        sext_ln388 : IN STD_LOGIC_VECTOR (58 downto 0) );
    end component;



begin
    grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55 : component ViT_act_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start,
        ap_done => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done,
        ap_idle => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_idle,
        ap_ready => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_ready,
        m_axi_inout4_AWVALID => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWVALID,
        m_axi_inout4_AWREADY => ap_const_logic_0,
        m_axi_inout4_AWADDR => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWADDR,
        m_axi_inout4_AWID => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWID,
        m_axi_inout4_AWLEN => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWLEN,
        m_axi_inout4_AWSIZE => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWSIZE,
        m_axi_inout4_AWBURST => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWBURST,
        m_axi_inout4_AWLOCK => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWLOCK,
        m_axi_inout4_AWCACHE => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWCACHE,
        m_axi_inout4_AWPROT => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWPROT,
        m_axi_inout4_AWQOS => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWQOS,
        m_axi_inout4_AWREGION => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWREGION,
        m_axi_inout4_AWUSER => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_AWUSER,
        m_axi_inout4_WVALID => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WVALID,
        m_axi_inout4_WREADY => ap_const_logic_0,
        m_axi_inout4_WDATA => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WDATA,
        m_axi_inout4_WSTRB => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WSTRB,
        m_axi_inout4_WLAST => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WLAST,
        m_axi_inout4_WID => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WID,
        m_axi_inout4_WUSER => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_WUSER,
        m_axi_inout4_ARVALID => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARVALID,
        m_axi_inout4_ARREADY => m_axi_inout4_ARREADY,
        m_axi_inout4_ARADDR => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARADDR,
        m_axi_inout4_ARID => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARID,
        m_axi_inout4_ARLEN => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLEN,
        m_axi_inout4_ARSIZE => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARSIZE,
        m_axi_inout4_ARBURST => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARBURST,
        m_axi_inout4_ARLOCK => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLOCK,
        m_axi_inout4_ARCACHE => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARCACHE,
        m_axi_inout4_ARPROT => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARPROT,
        m_axi_inout4_ARQOS => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARQOS,
        m_axi_inout4_ARREGION => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARREGION,
        m_axi_inout4_ARUSER => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARUSER,
        m_axi_inout4_RVALID => m_axi_inout4_RVALID,
        m_axi_inout4_RREADY => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_RREADY,
        m_axi_inout4_RDATA => m_axi_inout4_RDATA,
        m_axi_inout4_RLAST => m_axi_inout4_RLAST,
        m_axi_inout4_RID => m_axi_inout4_RID,
        m_axi_inout4_RFIFONUM => m_axi_inout4_RFIFONUM,
        m_axi_inout4_RUSER => m_axi_inout4_RUSER,
        m_axi_inout4_RRESP => m_axi_inout4_RRESP,
        m_axi_inout4_BVALID => ap_const_logic_0,
        m_axi_inout4_BREADY => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_BREADY,
        m_axi_inout4_BRESP => ap_const_lv2_0,
        m_axi_inout4_BID => ap_const_lv1_0,
        m_axi_inout4_BUSER => ap_const_lv1_0,
        attn_softmax_info_stream_din => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_din,
        attn_softmax_info_stream_num_data_valid => ap_const_lv2_0,
        attn_softmax_info_stream_fifo_cap => ap_const_lv2_0,
        attn_softmax_info_stream_full_n => attn_softmax_info_stream_full_n,
        attn_softmax_info_stream_write => grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_write,
        sext_ln388 => trunc_ln_reg_85);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_ready = ap_const_logic_1)) then 
                    grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln_reg_85 <= attn_softmax_info(63 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, m_axi_inout4_ARREADY, grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m_axi_inout4_ARREADY = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, m_axi_inout4_ARREADY)
    begin
        if (((m_axi_inout4_ARREADY = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done)
    begin
        if ((grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    attn_softmax_info_stream_din <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_din;

    attn_softmax_info_stream_write_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            attn_softmax_info_stream_write <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_attn_softmax_info_stream_write;
        else 
            attn_softmax_info_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_ap_start_reg;

    inout4_blk_n_AR_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m_axi_inout4_ARREADY)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            inout4_blk_n_AR <= m_axi_inout4_ARREADY;
        else 
            inout4_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    m_axi_inout4_ARADDR_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m_axi_inout4_ARREADY, grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARADDR, ap_CS_fsm_state8, ap_CS_fsm_state9, sext_ln388_fu_74_p1)
    begin
        if ((not(((m_axi_inout4_ARREADY = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_inout4_ARADDR <= sext_ln388_fu_74_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARADDR <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARADDR;
        else 
            m_axi_inout4_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_inout4_ARBURST_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARBURST, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARBURST <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARBURST;
        else 
            m_axi_inout4_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_inout4_ARCACHE_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARCACHE, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARCACHE <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARCACHE;
        else 
            m_axi_inout4_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_inout4_ARID_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARID, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARID <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARID;
        else 
            m_axi_inout4_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_inout4_ARLEN_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m_axi_inout4_ARREADY, grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLEN, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((not(((m_axi_inout4_ARREADY = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_inout4_ARLEN <= ap_const_lv32_81;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARLEN <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLEN;
        else 
            m_axi_inout4_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_inout4_ARLOCK_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLOCK, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARLOCK <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARLOCK;
        else 
            m_axi_inout4_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_inout4_ARPROT_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARPROT, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARPROT <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARPROT;
        else 
            m_axi_inout4_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_inout4_ARQOS_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARQOS, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARQOS <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARQOS;
        else 
            m_axi_inout4_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_inout4_ARREGION_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARREGION, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARREGION <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARREGION;
        else 
            m_axi_inout4_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_inout4_ARSIZE_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARSIZE, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARSIZE <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARSIZE;
        else 
            m_axi_inout4_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_inout4_ARUSER_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARUSER, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARUSER <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARUSER;
        else 
            m_axi_inout4_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_inout4_ARVALID_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m_axi_inout4_ARREADY, grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARVALID, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((not(((m_axi_inout4_ARREADY = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_inout4_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_ARVALID <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_ARVALID;
        else 
            m_axi_inout4_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_inout4_AWADDR <= ap_const_lv64_0;
    m_axi_inout4_AWBURST <= ap_const_lv2_0;
    m_axi_inout4_AWCACHE <= ap_const_lv4_0;
    m_axi_inout4_AWID <= ap_const_lv1_0;
    m_axi_inout4_AWLEN <= ap_const_lv32_0;
    m_axi_inout4_AWLOCK <= ap_const_lv2_0;
    m_axi_inout4_AWPROT <= ap_const_lv3_0;
    m_axi_inout4_AWQOS <= ap_const_lv4_0;
    m_axi_inout4_AWREGION <= ap_const_lv4_0;
    m_axi_inout4_AWSIZE <= ap_const_lv3_0;
    m_axi_inout4_AWUSER <= ap_const_lv1_0;
    m_axi_inout4_AWVALID <= ap_const_logic_0;
    m_axi_inout4_BREADY <= ap_const_logic_0;

    m_axi_inout4_RREADY_assign_proc : process(grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_RREADY, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_inout4_RREADY <= grp_read_attn_softmax_info_Pipeline_ln388_for_each_q_patch_fu_55_m_axi_inout4_RREADY;
        else 
            m_axi_inout4_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_inout4_WDATA <= ap_const_lv256_lc_1;
    m_axi_inout4_WID <= ap_const_lv1_0;
    m_axi_inout4_WLAST <= ap_const_logic_0;
    m_axi_inout4_WSTRB <= ap_const_lv32_0;
    m_axi_inout4_WUSER <= ap_const_lv1_0;
    m_axi_inout4_WVALID <= ap_const_logic_0;
        sext_ln388_fu_74_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_64_p4),64));

    trunc_ln_fu_64_p4 <= attn_softmax_info(63 downto 5);
end behav;
