// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ViT_act_compute_attn_matmul_v (
        m_axi_inout2_AWVALID,
        m_axi_inout2_AWREADY,
        m_axi_inout2_AWADDR,
        m_axi_inout2_AWID,
        m_axi_inout2_AWLEN,
        m_axi_inout2_AWSIZE,
        m_axi_inout2_AWBURST,
        m_axi_inout2_AWLOCK,
        m_axi_inout2_AWCACHE,
        m_axi_inout2_AWPROT,
        m_axi_inout2_AWQOS,
        m_axi_inout2_AWREGION,
        m_axi_inout2_AWUSER,
        m_axi_inout2_WVALID,
        m_axi_inout2_WREADY,
        m_axi_inout2_WDATA,
        m_axi_inout2_WSTRB,
        m_axi_inout2_WLAST,
        m_axi_inout2_WID,
        m_axi_inout2_WUSER,
        m_axi_inout2_ARVALID,
        m_axi_inout2_ARREADY,
        m_axi_inout2_ARADDR,
        m_axi_inout2_ARID,
        m_axi_inout2_ARLEN,
        m_axi_inout2_ARSIZE,
        m_axi_inout2_ARBURST,
        m_axi_inout2_ARLOCK,
        m_axi_inout2_ARCACHE,
        m_axi_inout2_ARPROT,
        m_axi_inout2_ARQOS,
        m_axi_inout2_ARREGION,
        m_axi_inout2_ARUSER,
        m_axi_inout2_RVALID,
        m_axi_inout2_RREADY,
        m_axi_inout2_RDATA,
        m_axi_inout2_RLAST,
        m_axi_inout2_RID,
        m_axi_inout2_RFIFONUM,
        m_axi_inout2_RUSER,
        m_axi_inout2_RRESP,
        m_axi_inout2_BVALID,
        m_axi_inout2_BREADY,
        m_axi_inout2_BRESP,
        m_axi_inout2_BID,
        m_axi_inout2_BUSER,
        v,
        m_axi_inout1_AWVALID,
        m_axi_inout1_AWREADY,
        m_axi_inout1_AWADDR,
        m_axi_inout1_AWID,
        m_axi_inout1_AWLEN,
        m_axi_inout1_AWSIZE,
        m_axi_inout1_AWBURST,
        m_axi_inout1_AWLOCK,
        m_axi_inout1_AWCACHE,
        m_axi_inout1_AWPROT,
        m_axi_inout1_AWQOS,
        m_axi_inout1_AWREGION,
        m_axi_inout1_AWUSER,
        m_axi_inout1_WVALID,
        m_axi_inout1_WREADY,
        m_axi_inout1_WDATA,
        m_axi_inout1_WSTRB,
        m_axi_inout1_WLAST,
        m_axi_inout1_WID,
        m_axi_inout1_WUSER,
        m_axi_inout1_ARVALID,
        m_axi_inout1_ARREADY,
        m_axi_inout1_ARADDR,
        m_axi_inout1_ARID,
        m_axi_inout1_ARLEN,
        m_axi_inout1_ARSIZE,
        m_axi_inout1_ARBURST,
        m_axi_inout1_ARLOCK,
        m_axi_inout1_ARCACHE,
        m_axi_inout1_ARPROT,
        m_axi_inout1_ARQOS,
        m_axi_inout1_ARREGION,
        m_axi_inout1_ARUSER,
        m_axi_inout1_RVALID,
        m_axi_inout1_RREADY,
        m_axi_inout1_RDATA,
        m_axi_inout1_RLAST,
        m_axi_inout1_RID,
        m_axi_inout1_RFIFONUM,
        m_axi_inout1_RUSER,
        m_axi_inout1_RRESP,
        m_axi_inout1_BVALID,
        m_axi_inout1_BREADY,
        m_axi_inout1_BRESP,
        m_axi_inout1_BID,
        m_axi_inout1_BUSER,
        attn,
        m_axi_inout4_AWVALID,
        m_axi_inout4_AWREADY,
        m_axi_inout4_AWADDR,
        m_axi_inout4_AWID,
        m_axi_inout4_AWLEN,
        m_axi_inout4_AWSIZE,
        m_axi_inout4_AWBURST,
        m_axi_inout4_AWLOCK,
        m_axi_inout4_AWCACHE,
        m_axi_inout4_AWPROT,
        m_axi_inout4_AWQOS,
        m_axi_inout4_AWREGION,
        m_axi_inout4_AWUSER,
        m_axi_inout4_WVALID,
        m_axi_inout4_WREADY,
        m_axi_inout4_WDATA,
        m_axi_inout4_WSTRB,
        m_axi_inout4_WLAST,
        m_axi_inout4_WID,
        m_axi_inout4_WUSER,
        m_axi_inout4_ARVALID,
        m_axi_inout4_ARREADY,
        m_axi_inout4_ARADDR,
        m_axi_inout4_ARID,
        m_axi_inout4_ARLEN,
        m_axi_inout4_ARSIZE,
        m_axi_inout4_ARBURST,
        m_axi_inout4_ARLOCK,
        m_axi_inout4_ARCACHE,
        m_axi_inout4_ARPROT,
        m_axi_inout4_ARQOS,
        m_axi_inout4_ARREGION,
        m_axi_inout4_ARUSER,
        m_axi_inout4_RVALID,
        m_axi_inout4_RREADY,
        m_axi_inout4_RDATA,
        m_axi_inout4_RLAST,
        m_axi_inout4_RID,
        m_axi_inout4_RFIFONUM,
        m_axi_inout4_RUSER,
        m_axi_inout4_RRESP,
        m_axi_inout4_BVALID,
        m_axi_inout4_BREADY,
        m_axi_inout4_BRESP,
        m_axi_inout4_BID,
        m_axi_inout4_BUSER,
        attn_softmax_info,
        attn_matmul_v,
        ap_clk,
        ap_rst,
        attn_matmul_v_ap_vld,
        ap_start,
        v_ap_vld,
        attn_ap_vld,
        attn_softmax_info_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_inout2_AWVALID;
input   m_axi_inout2_AWREADY;
output  [63:0] m_axi_inout2_AWADDR;
output  [0:0] m_axi_inout2_AWID;
output  [31:0] m_axi_inout2_AWLEN;
output  [2:0] m_axi_inout2_AWSIZE;
output  [1:0] m_axi_inout2_AWBURST;
output  [1:0] m_axi_inout2_AWLOCK;
output  [3:0] m_axi_inout2_AWCACHE;
output  [2:0] m_axi_inout2_AWPROT;
output  [3:0] m_axi_inout2_AWQOS;
output  [3:0] m_axi_inout2_AWREGION;
output  [0:0] m_axi_inout2_AWUSER;
output   m_axi_inout2_WVALID;
input   m_axi_inout2_WREADY;
output  [255:0] m_axi_inout2_WDATA;
output  [31:0] m_axi_inout2_WSTRB;
output   m_axi_inout2_WLAST;
output  [0:0] m_axi_inout2_WID;
output  [0:0] m_axi_inout2_WUSER;
output   m_axi_inout2_ARVALID;
input   m_axi_inout2_ARREADY;
output  [63:0] m_axi_inout2_ARADDR;
output  [0:0] m_axi_inout2_ARID;
output  [31:0] m_axi_inout2_ARLEN;
output  [2:0] m_axi_inout2_ARSIZE;
output  [1:0] m_axi_inout2_ARBURST;
output  [1:0] m_axi_inout2_ARLOCK;
output  [3:0] m_axi_inout2_ARCACHE;
output  [2:0] m_axi_inout2_ARPROT;
output  [3:0] m_axi_inout2_ARQOS;
output  [3:0] m_axi_inout2_ARREGION;
output  [0:0] m_axi_inout2_ARUSER;
input   m_axi_inout2_RVALID;
output   m_axi_inout2_RREADY;
input  [255:0] m_axi_inout2_RDATA;
input   m_axi_inout2_RLAST;
input  [0:0] m_axi_inout2_RID;
input  [8:0] m_axi_inout2_RFIFONUM;
input  [0:0] m_axi_inout2_RUSER;
input  [1:0] m_axi_inout2_RRESP;
input   m_axi_inout2_BVALID;
output   m_axi_inout2_BREADY;
input  [1:0] m_axi_inout2_BRESP;
input  [0:0] m_axi_inout2_BID;
input  [0:0] m_axi_inout2_BUSER;
input  [63:0] v;
output   m_axi_inout1_AWVALID;
input   m_axi_inout1_AWREADY;
output  [63:0] m_axi_inout1_AWADDR;
output  [0:0] m_axi_inout1_AWID;
output  [31:0] m_axi_inout1_AWLEN;
output  [2:0] m_axi_inout1_AWSIZE;
output  [1:0] m_axi_inout1_AWBURST;
output  [1:0] m_axi_inout1_AWLOCK;
output  [3:0] m_axi_inout1_AWCACHE;
output  [2:0] m_axi_inout1_AWPROT;
output  [3:0] m_axi_inout1_AWQOS;
output  [3:0] m_axi_inout1_AWREGION;
output  [0:0] m_axi_inout1_AWUSER;
output   m_axi_inout1_WVALID;
input   m_axi_inout1_WREADY;
output  [255:0] m_axi_inout1_WDATA;
output  [31:0] m_axi_inout1_WSTRB;
output   m_axi_inout1_WLAST;
output  [0:0] m_axi_inout1_WID;
output  [0:0] m_axi_inout1_WUSER;
output   m_axi_inout1_ARVALID;
input   m_axi_inout1_ARREADY;
output  [63:0] m_axi_inout1_ARADDR;
output  [0:0] m_axi_inout1_ARID;
output  [31:0] m_axi_inout1_ARLEN;
output  [2:0] m_axi_inout1_ARSIZE;
output  [1:0] m_axi_inout1_ARBURST;
output  [1:0] m_axi_inout1_ARLOCK;
output  [3:0] m_axi_inout1_ARCACHE;
output  [2:0] m_axi_inout1_ARPROT;
output  [3:0] m_axi_inout1_ARQOS;
output  [3:0] m_axi_inout1_ARREGION;
output  [0:0] m_axi_inout1_ARUSER;
input   m_axi_inout1_RVALID;
output   m_axi_inout1_RREADY;
input  [255:0] m_axi_inout1_RDATA;
input   m_axi_inout1_RLAST;
input  [0:0] m_axi_inout1_RID;
input  [8:0] m_axi_inout1_RFIFONUM;
input  [0:0] m_axi_inout1_RUSER;
input  [1:0] m_axi_inout1_RRESP;
input   m_axi_inout1_BVALID;
output   m_axi_inout1_BREADY;
input  [1:0] m_axi_inout1_BRESP;
input  [0:0] m_axi_inout1_BID;
input  [0:0] m_axi_inout1_BUSER;
input  [63:0] attn;
output   m_axi_inout4_AWVALID;
input   m_axi_inout4_AWREADY;
output  [63:0] m_axi_inout4_AWADDR;
output  [0:0] m_axi_inout4_AWID;
output  [31:0] m_axi_inout4_AWLEN;
output  [2:0] m_axi_inout4_AWSIZE;
output  [1:0] m_axi_inout4_AWBURST;
output  [1:0] m_axi_inout4_AWLOCK;
output  [3:0] m_axi_inout4_AWCACHE;
output  [2:0] m_axi_inout4_AWPROT;
output  [3:0] m_axi_inout4_AWQOS;
output  [3:0] m_axi_inout4_AWREGION;
output  [0:0] m_axi_inout4_AWUSER;
output   m_axi_inout4_WVALID;
input   m_axi_inout4_WREADY;
output  [255:0] m_axi_inout4_WDATA;
output  [31:0] m_axi_inout4_WSTRB;
output   m_axi_inout4_WLAST;
output  [0:0] m_axi_inout4_WID;
output  [0:0] m_axi_inout4_WUSER;
output   m_axi_inout4_ARVALID;
input   m_axi_inout4_ARREADY;
output  [63:0] m_axi_inout4_ARADDR;
output  [0:0] m_axi_inout4_ARID;
output  [31:0] m_axi_inout4_ARLEN;
output  [2:0] m_axi_inout4_ARSIZE;
output  [1:0] m_axi_inout4_ARBURST;
output  [1:0] m_axi_inout4_ARLOCK;
output  [3:0] m_axi_inout4_ARCACHE;
output  [2:0] m_axi_inout4_ARPROT;
output  [3:0] m_axi_inout4_ARQOS;
output  [3:0] m_axi_inout4_ARREGION;
output  [0:0] m_axi_inout4_ARUSER;
input   m_axi_inout4_RVALID;
output   m_axi_inout4_RREADY;
input  [255:0] m_axi_inout4_RDATA;
input   m_axi_inout4_RLAST;
input  [0:0] m_axi_inout4_RID;
input  [8:0] m_axi_inout4_RFIFONUM;
input  [0:0] m_axi_inout4_RUSER;
input  [1:0] m_axi_inout4_RRESP;
input   m_axi_inout4_BVALID;
output   m_axi_inout4_BREADY;
input  [1:0] m_axi_inout4_BRESP;
input  [0:0] m_axi_inout4_BID;
input  [0:0] m_axi_inout4_BUSER;
input  [63:0] attn_softmax_info;
input  [63:0] attn_matmul_v;
input   ap_clk;
input   ap_rst;
input   attn_matmul_v_ap_vld;
input   ap_start;
input   v_ap_vld;
input   attn_ap_vld;
input   attn_softmax_info_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc25_U0_ap_start;
wire    entry_proc25_U0_ap_done;
wire    entry_proc25_U0_ap_continue;
wire    entry_proc25_U0_ap_idle;
wire    entry_proc25_U0_ap_ready;
wire    entry_proc25_U0_start_out;
wire    entry_proc25_U0_start_write;
wire   [63:0] entry_proc25_U0_attn_matmul_v_c_din;
wire    entry_proc25_U0_attn_matmul_v_c_write;
wire    read_k_v_6_U0_ap_start;
wire    read_k_v_6_U0_ap_done;
wire    read_k_v_6_U0_ap_continue;
wire    read_k_v_6_U0_ap_idle;
wire    read_k_v_6_U0_ap_ready;
wire    read_k_v_6_U0_m_axi_inout2_AWVALID;
wire   [63:0] read_k_v_6_U0_m_axi_inout2_AWADDR;
wire   [0:0] read_k_v_6_U0_m_axi_inout2_AWID;
wire   [31:0] read_k_v_6_U0_m_axi_inout2_AWLEN;
wire   [2:0] read_k_v_6_U0_m_axi_inout2_AWSIZE;
wire   [1:0] read_k_v_6_U0_m_axi_inout2_AWBURST;
wire   [1:0] read_k_v_6_U0_m_axi_inout2_AWLOCK;
wire   [3:0] read_k_v_6_U0_m_axi_inout2_AWCACHE;
wire   [2:0] read_k_v_6_U0_m_axi_inout2_AWPROT;
wire   [3:0] read_k_v_6_U0_m_axi_inout2_AWQOS;
wire   [3:0] read_k_v_6_U0_m_axi_inout2_AWREGION;
wire   [0:0] read_k_v_6_U0_m_axi_inout2_AWUSER;
wire    read_k_v_6_U0_m_axi_inout2_WVALID;
wire   [255:0] read_k_v_6_U0_m_axi_inout2_WDATA;
wire   [31:0] read_k_v_6_U0_m_axi_inout2_WSTRB;
wire    read_k_v_6_U0_m_axi_inout2_WLAST;
wire   [0:0] read_k_v_6_U0_m_axi_inout2_WID;
wire   [0:0] read_k_v_6_U0_m_axi_inout2_WUSER;
wire    read_k_v_6_U0_m_axi_inout2_ARVALID;
wire   [63:0] read_k_v_6_U0_m_axi_inout2_ARADDR;
wire   [0:0] read_k_v_6_U0_m_axi_inout2_ARID;
wire   [31:0] read_k_v_6_U0_m_axi_inout2_ARLEN;
wire   [2:0] read_k_v_6_U0_m_axi_inout2_ARSIZE;
wire   [1:0] read_k_v_6_U0_m_axi_inout2_ARBURST;
wire   [1:0] read_k_v_6_U0_m_axi_inout2_ARLOCK;
wire   [3:0] read_k_v_6_U0_m_axi_inout2_ARCACHE;
wire   [2:0] read_k_v_6_U0_m_axi_inout2_ARPROT;
wire   [3:0] read_k_v_6_U0_m_axi_inout2_ARQOS;
wire   [3:0] read_k_v_6_U0_m_axi_inout2_ARREGION;
wire   [0:0] read_k_v_6_U0_m_axi_inout2_ARUSER;
wire    read_k_v_6_U0_m_axi_inout2_RREADY;
wire    read_k_v_6_U0_m_axi_inout2_BREADY;
wire   [255:0] read_k_v_6_U0_v_stream_din;
wire    read_k_v_6_U0_v_stream_write;
wire    read_k_v_6_U0_start_out;
wire    read_k_v_6_U0_start_write;
wire    read_attn_U0_ap_start;
wire    read_attn_U0_ap_done;
wire    read_attn_U0_ap_continue;
wire    read_attn_U0_ap_idle;
wire    read_attn_U0_ap_ready;
wire    read_attn_U0_m_axi_inout1_AWVALID;
wire   [63:0] read_attn_U0_m_axi_inout1_AWADDR;
wire   [0:0] read_attn_U0_m_axi_inout1_AWID;
wire   [31:0] read_attn_U0_m_axi_inout1_AWLEN;
wire   [2:0] read_attn_U0_m_axi_inout1_AWSIZE;
wire   [1:0] read_attn_U0_m_axi_inout1_AWBURST;
wire   [1:0] read_attn_U0_m_axi_inout1_AWLOCK;
wire   [3:0] read_attn_U0_m_axi_inout1_AWCACHE;
wire   [2:0] read_attn_U0_m_axi_inout1_AWPROT;
wire   [3:0] read_attn_U0_m_axi_inout1_AWQOS;
wire   [3:0] read_attn_U0_m_axi_inout1_AWREGION;
wire   [0:0] read_attn_U0_m_axi_inout1_AWUSER;
wire    read_attn_U0_m_axi_inout1_WVALID;
wire   [255:0] read_attn_U0_m_axi_inout1_WDATA;
wire   [31:0] read_attn_U0_m_axi_inout1_WSTRB;
wire    read_attn_U0_m_axi_inout1_WLAST;
wire   [0:0] read_attn_U0_m_axi_inout1_WID;
wire   [0:0] read_attn_U0_m_axi_inout1_WUSER;
wire    read_attn_U0_m_axi_inout1_ARVALID;
wire   [63:0] read_attn_U0_m_axi_inout1_ARADDR;
wire   [0:0] read_attn_U0_m_axi_inout1_ARID;
wire   [31:0] read_attn_U0_m_axi_inout1_ARLEN;
wire   [2:0] read_attn_U0_m_axi_inout1_ARSIZE;
wire   [1:0] read_attn_U0_m_axi_inout1_ARBURST;
wire   [1:0] read_attn_U0_m_axi_inout1_ARLOCK;
wire   [3:0] read_attn_U0_m_axi_inout1_ARCACHE;
wire   [2:0] read_attn_U0_m_axi_inout1_ARPROT;
wire   [3:0] read_attn_U0_m_axi_inout1_ARQOS;
wire   [3:0] read_attn_U0_m_axi_inout1_ARREGION;
wire   [0:0] read_attn_U0_m_axi_inout1_ARUSER;
wire    read_attn_U0_m_axi_inout1_RREADY;
wire    read_attn_U0_m_axi_inout1_BREADY;
wire   [127:0] read_attn_U0_attn_stream_din;
wire    read_attn_U0_attn_stream_write;
wire    read_attn_U0_start_out;
wire    read_attn_U0_start_write;
wire    read_attn_softmax_info_U0_ap_start;
wire    read_attn_softmax_info_U0_ap_done;
wire    read_attn_softmax_info_U0_ap_continue;
wire    read_attn_softmax_info_U0_ap_idle;
wire    read_attn_softmax_info_U0_ap_ready;
wire   [255:0] read_attn_softmax_info_U0_attn_softmax_info_stream_din;
wire    read_attn_softmax_info_U0_attn_softmax_info_stream_write;
wire    read_attn_softmax_info_U0_m_axi_inout4_AWVALID;
wire   [63:0] read_attn_softmax_info_U0_m_axi_inout4_AWADDR;
wire   [0:0] read_attn_softmax_info_U0_m_axi_inout4_AWID;
wire   [31:0] read_attn_softmax_info_U0_m_axi_inout4_AWLEN;
wire   [2:0] read_attn_softmax_info_U0_m_axi_inout4_AWSIZE;
wire   [1:0] read_attn_softmax_info_U0_m_axi_inout4_AWBURST;
wire   [1:0] read_attn_softmax_info_U0_m_axi_inout4_AWLOCK;
wire   [3:0] read_attn_softmax_info_U0_m_axi_inout4_AWCACHE;
wire   [2:0] read_attn_softmax_info_U0_m_axi_inout4_AWPROT;
wire   [3:0] read_attn_softmax_info_U0_m_axi_inout4_AWQOS;
wire   [3:0] read_attn_softmax_info_U0_m_axi_inout4_AWREGION;
wire   [0:0] read_attn_softmax_info_U0_m_axi_inout4_AWUSER;
wire    read_attn_softmax_info_U0_m_axi_inout4_WVALID;
wire   [255:0] read_attn_softmax_info_U0_m_axi_inout4_WDATA;
wire   [31:0] read_attn_softmax_info_U0_m_axi_inout4_WSTRB;
wire    read_attn_softmax_info_U0_m_axi_inout4_WLAST;
wire   [0:0] read_attn_softmax_info_U0_m_axi_inout4_WID;
wire   [0:0] read_attn_softmax_info_U0_m_axi_inout4_WUSER;
wire    read_attn_softmax_info_U0_m_axi_inout4_ARVALID;
wire   [63:0] read_attn_softmax_info_U0_m_axi_inout4_ARADDR;
wire   [0:0] read_attn_softmax_info_U0_m_axi_inout4_ARID;
wire   [31:0] read_attn_softmax_info_U0_m_axi_inout4_ARLEN;
wire   [2:0] read_attn_softmax_info_U0_m_axi_inout4_ARSIZE;
wire   [1:0] read_attn_softmax_info_U0_m_axi_inout4_ARBURST;
wire   [1:0] read_attn_softmax_info_U0_m_axi_inout4_ARLOCK;
wire   [3:0] read_attn_softmax_info_U0_m_axi_inout4_ARCACHE;
wire   [2:0] read_attn_softmax_info_U0_m_axi_inout4_ARPROT;
wire   [3:0] read_attn_softmax_info_U0_m_axi_inout4_ARQOS;
wire   [3:0] read_attn_softmax_info_U0_m_axi_inout4_ARREGION;
wire   [0:0] read_attn_softmax_info_U0_m_axi_inout4_ARUSER;
wire    read_attn_softmax_info_U0_m_axi_inout4_RREADY;
wire    read_attn_softmax_info_U0_m_axi_inout4_BREADY;
wire    prepare_attn_U0_ap_start;
wire    prepare_attn_U0_ap_done;
wire    prepare_attn_U0_ap_continue;
wire    prepare_attn_U0_ap_idle;
wire    prepare_attn_U0_ap_ready;
wire    prepare_attn_U0_attn_stream_read;
wire   [511:0] prepare_attn_U0_qxk_out_stream_din;
wire    prepare_attn_U0_qxk_out_stream_write;
wire    compute_attn_matmul_v_7_U0_ap_start;
wire    compute_attn_matmul_v_7_U0_ap_done;
wire    compute_attn_matmul_v_7_U0_ap_continue;
wire    compute_attn_matmul_v_7_U0_ap_idle;
wire    compute_attn_matmul_v_7_U0_ap_ready;
wire    compute_attn_matmul_v_7_U0_attn_softmax_info_stream_read;
wire    compute_attn_matmul_v_7_U0_qxk_out_stream_read;
wire    compute_attn_matmul_v_7_U0_v_stream_read;
wire   [255:0] compute_attn_matmul_v_7_U0_attn_matmul_v_stream_din;
wire    compute_attn_matmul_v_7_U0_attn_matmul_v_stream_write;
wire    write_attn_matmul_v_U0_ap_start;
wire    write_attn_matmul_v_U0_ap_done;
wire    write_attn_matmul_v_U0_ap_continue;
wire    write_attn_matmul_v_U0_ap_idle;
wire    write_attn_matmul_v_U0_ap_ready;
wire    write_attn_matmul_v_U0_m_axi_inout1_AWVALID;
wire   [63:0] write_attn_matmul_v_U0_m_axi_inout1_AWADDR;
wire   [0:0] write_attn_matmul_v_U0_m_axi_inout1_AWID;
wire   [31:0] write_attn_matmul_v_U0_m_axi_inout1_AWLEN;
wire   [2:0] write_attn_matmul_v_U0_m_axi_inout1_AWSIZE;
wire   [1:0] write_attn_matmul_v_U0_m_axi_inout1_AWBURST;
wire   [1:0] write_attn_matmul_v_U0_m_axi_inout1_AWLOCK;
wire   [3:0] write_attn_matmul_v_U0_m_axi_inout1_AWCACHE;
wire   [2:0] write_attn_matmul_v_U0_m_axi_inout1_AWPROT;
wire   [3:0] write_attn_matmul_v_U0_m_axi_inout1_AWQOS;
wire   [3:0] write_attn_matmul_v_U0_m_axi_inout1_AWREGION;
wire   [0:0] write_attn_matmul_v_U0_m_axi_inout1_AWUSER;
wire    write_attn_matmul_v_U0_m_axi_inout1_WVALID;
wire   [255:0] write_attn_matmul_v_U0_m_axi_inout1_WDATA;
wire   [31:0] write_attn_matmul_v_U0_m_axi_inout1_WSTRB;
wire    write_attn_matmul_v_U0_m_axi_inout1_WLAST;
wire   [0:0] write_attn_matmul_v_U0_m_axi_inout1_WID;
wire   [0:0] write_attn_matmul_v_U0_m_axi_inout1_WUSER;
wire    write_attn_matmul_v_U0_m_axi_inout1_ARVALID;
wire   [63:0] write_attn_matmul_v_U0_m_axi_inout1_ARADDR;
wire   [0:0] write_attn_matmul_v_U0_m_axi_inout1_ARID;
wire   [31:0] write_attn_matmul_v_U0_m_axi_inout1_ARLEN;
wire   [2:0] write_attn_matmul_v_U0_m_axi_inout1_ARSIZE;
wire   [1:0] write_attn_matmul_v_U0_m_axi_inout1_ARBURST;
wire   [1:0] write_attn_matmul_v_U0_m_axi_inout1_ARLOCK;
wire   [3:0] write_attn_matmul_v_U0_m_axi_inout1_ARCACHE;
wire   [2:0] write_attn_matmul_v_U0_m_axi_inout1_ARPROT;
wire   [3:0] write_attn_matmul_v_U0_m_axi_inout1_ARQOS;
wire   [3:0] write_attn_matmul_v_U0_m_axi_inout1_ARREGION;
wire   [0:0] write_attn_matmul_v_U0_m_axi_inout1_ARUSER;
wire    write_attn_matmul_v_U0_m_axi_inout1_RREADY;
wire    write_attn_matmul_v_U0_m_axi_inout1_BREADY;
wire    write_attn_matmul_v_U0_attn_matmul_v_read;
wire    write_attn_matmul_v_U0_attn_matmul_v_stream_read;
wire    attn_matmul_v_c_full_n;
wire   [63:0] attn_matmul_v_c_dout;
wire   [3:0] attn_matmul_v_c_num_data_valid;
wire   [3:0] attn_matmul_v_c_fifo_cap;
wire    attn_matmul_v_c_empty_n;
wire    v_stream_full_n;
wire   [255:0] v_stream_dout;
wire   [1:0] v_stream_num_data_valid;
wire   [1:0] v_stream_fifo_cap;
wire    v_stream_empty_n;
wire    attn_stream_full_n;
wire   [127:0] attn_stream_dout;
wire   [1:0] attn_stream_num_data_valid;
wire   [1:0] attn_stream_fifo_cap;
wire    attn_stream_empty_n;
wire    attn_softmax_info_stream_full_n;
wire   [255:0] attn_softmax_info_stream_dout;
wire   [1:0] attn_softmax_info_stream_num_data_valid;
wire   [1:0] attn_softmax_info_stream_fifo_cap;
wire    attn_softmax_info_stream_empty_n;
wire    qxk_out_stream_full_n;
wire   [511:0] qxk_out_stream_dout;
wire   [1:0] qxk_out_stream_num_data_valid;
wire   [1:0] qxk_out_stream_fifo_cap;
wire    qxk_out_stream_empty_n;
wire    attn_matmul_v_stream_full_n;
wire   [255:0] attn_matmul_v_stream_dout;
wire   [1:0] attn_matmul_v_stream_num_data_valid;
wire   [1:0] attn_matmul_v_stream_fifo_cap;
wire    attn_matmul_v_stream_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc25_U0_ap_ready;
wire    ap_sync_entry_proc25_U0_ap_ready;
reg    ap_sync_reg_read_k_v_6_U0_ap_ready;
wire    ap_sync_read_k_v_6_U0_ap_ready;
reg    ap_sync_reg_read_attn_U0_ap_ready;
wire    ap_sync_read_attn_U0_ap_ready;
reg    ap_sync_reg_read_attn_softmax_info_U0_ap_ready;
wire    ap_sync_read_attn_softmax_info_U0_ap_ready;
wire   [0:0] start_for_write_attn_matmul_v_U0_din;
wire    start_for_write_attn_matmul_v_U0_full_n;
wire   [0:0] start_for_write_attn_matmul_v_U0_dout;
wire    start_for_write_attn_matmul_v_U0_empty_n;
wire   [0:0] start_for_compute_attn_matmul_v_7_U0_din;
wire    start_for_compute_attn_matmul_v_7_U0_full_n;
wire   [0:0] start_for_compute_attn_matmul_v_7_U0_dout;
wire    start_for_compute_attn_matmul_v_7_U0_empty_n;
wire   [0:0] start_for_prepare_attn_U0_din;
wire    start_for_prepare_attn_U0_full_n;
wire   [0:0] start_for_prepare_attn_U0_dout;
wire    start_for_prepare_attn_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc25_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_k_v_6_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_attn_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_attn_softmax_info_U0_ap_ready = 1'b0;
end

ViT_act_entry_proc25 entry_proc25_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc25_U0_ap_start),
    .start_full_n(start_for_write_attn_matmul_v_U0_full_n),
    .ap_done(entry_proc25_U0_ap_done),
    .ap_continue(entry_proc25_U0_ap_continue),
    .ap_idle(entry_proc25_U0_ap_idle),
    .ap_ready(entry_proc25_U0_ap_ready),
    .start_out(entry_proc25_U0_start_out),
    .start_write(entry_proc25_U0_start_write),
    .attn_matmul_v(attn_matmul_v),
    .attn_matmul_v_c_din(entry_proc25_U0_attn_matmul_v_c_din),
    .attn_matmul_v_c_num_data_valid(attn_matmul_v_c_num_data_valid),
    .attn_matmul_v_c_fifo_cap(attn_matmul_v_c_fifo_cap),
    .attn_matmul_v_c_full_n(attn_matmul_v_c_full_n),
    .attn_matmul_v_c_write(entry_proc25_U0_attn_matmul_v_c_write)
);

ViT_act_read_k_v_6 read_k_v_6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_k_v_6_U0_ap_start),
    .start_full_n(start_for_compute_attn_matmul_v_7_U0_full_n),
    .ap_done(read_k_v_6_U0_ap_done),
    .ap_continue(read_k_v_6_U0_ap_continue),
    .ap_idle(read_k_v_6_U0_ap_idle),
    .ap_ready(read_k_v_6_U0_ap_ready),
    .m_axi_inout2_AWVALID(read_k_v_6_U0_m_axi_inout2_AWVALID),
    .m_axi_inout2_AWREADY(1'b0),
    .m_axi_inout2_AWADDR(read_k_v_6_U0_m_axi_inout2_AWADDR),
    .m_axi_inout2_AWID(read_k_v_6_U0_m_axi_inout2_AWID),
    .m_axi_inout2_AWLEN(read_k_v_6_U0_m_axi_inout2_AWLEN),
    .m_axi_inout2_AWSIZE(read_k_v_6_U0_m_axi_inout2_AWSIZE),
    .m_axi_inout2_AWBURST(read_k_v_6_U0_m_axi_inout2_AWBURST),
    .m_axi_inout2_AWLOCK(read_k_v_6_U0_m_axi_inout2_AWLOCK),
    .m_axi_inout2_AWCACHE(read_k_v_6_U0_m_axi_inout2_AWCACHE),
    .m_axi_inout2_AWPROT(read_k_v_6_U0_m_axi_inout2_AWPROT),
    .m_axi_inout2_AWQOS(read_k_v_6_U0_m_axi_inout2_AWQOS),
    .m_axi_inout2_AWREGION(read_k_v_6_U0_m_axi_inout2_AWREGION),
    .m_axi_inout2_AWUSER(read_k_v_6_U0_m_axi_inout2_AWUSER),
    .m_axi_inout2_WVALID(read_k_v_6_U0_m_axi_inout2_WVALID),
    .m_axi_inout2_WREADY(1'b0),
    .m_axi_inout2_WDATA(read_k_v_6_U0_m_axi_inout2_WDATA),
    .m_axi_inout2_WSTRB(read_k_v_6_U0_m_axi_inout2_WSTRB),
    .m_axi_inout2_WLAST(read_k_v_6_U0_m_axi_inout2_WLAST),
    .m_axi_inout2_WID(read_k_v_6_U0_m_axi_inout2_WID),
    .m_axi_inout2_WUSER(read_k_v_6_U0_m_axi_inout2_WUSER),
    .m_axi_inout2_ARVALID(read_k_v_6_U0_m_axi_inout2_ARVALID),
    .m_axi_inout2_ARREADY(m_axi_inout2_ARREADY),
    .m_axi_inout2_ARADDR(read_k_v_6_U0_m_axi_inout2_ARADDR),
    .m_axi_inout2_ARID(read_k_v_6_U0_m_axi_inout2_ARID),
    .m_axi_inout2_ARLEN(read_k_v_6_U0_m_axi_inout2_ARLEN),
    .m_axi_inout2_ARSIZE(read_k_v_6_U0_m_axi_inout2_ARSIZE),
    .m_axi_inout2_ARBURST(read_k_v_6_U0_m_axi_inout2_ARBURST),
    .m_axi_inout2_ARLOCK(read_k_v_6_U0_m_axi_inout2_ARLOCK),
    .m_axi_inout2_ARCACHE(read_k_v_6_U0_m_axi_inout2_ARCACHE),
    .m_axi_inout2_ARPROT(read_k_v_6_U0_m_axi_inout2_ARPROT),
    .m_axi_inout2_ARQOS(read_k_v_6_U0_m_axi_inout2_ARQOS),
    .m_axi_inout2_ARREGION(read_k_v_6_U0_m_axi_inout2_ARREGION),
    .m_axi_inout2_ARUSER(read_k_v_6_U0_m_axi_inout2_ARUSER),
    .m_axi_inout2_RVALID(m_axi_inout2_RVALID),
    .m_axi_inout2_RREADY(read_k_v_6_U0_m_axi_inout2_RREADY),
    .m_axi_inout2_RDATA(m_axi_inout2_RDATA),
    .m_axi_inout2_RLAST(m_axi_inout2_RLAST),
    .m_axi_inout2_RID(m_axi_inout2_RID),
    .m_axi_inout2_RFIFONUM(m_axi_inout2_RFIFONUM),
    .m_axi_inout2_RUSER(m_axi_inout2_RUSER),
    .m_axi_inout2_RRESP(m_axi_inout2_RRESP),
    .m_axi_inout2_BVALID(1'b0),
    .m_axi_inout2_BREADY(read_k_v_6_U0_m_axi_inout2_BREADY),
    .m_axi_inout2_BRESP(2'd0),
    .m_axi_inout2_BID(1'd0),
    .m_axi_inout2_BUSER(1'd0),
    .v_stream_din(read_k_v_6_U0_v_stream_din),
    .v_stream_num_data_valid(v_stream_num_data_valid),
    .v_stream_fifo_cap(v_stream_fifo_cap),
    .v_stream_full_n(v_stream_full_n),
    .v_stream_write(read_k_v_6_U0_v_stream_write),
    .start_out(read_k_v_6_U0_start_out),
    .start_write(read_k_v_6_U0_start_write),
    .k(v)
);

ViT_act_read_attn read_attn_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_attn_U0_ap_start),
    .start_full_n(start_for_prepare_attn_U0_full_n),
    .ap_done(read_attn_U0_ap_done),
    .ap_continue(read_attn_U0_ap_continue),
    .ap_idle(read_attn_U0_ap_idle),
    .ap_ready(read_attn_U0_ap_ready),
    .m_axi_inout1_AWVALID(read_attn_U0_m_axi_inout1_AWVALID),
    .m_axi_inout1_AWREADY(1'b0),
    .m_axi_inout1_AWADDR(read_attn_U0_m_axi_inout1_AWADDR),
    .m_axi_inout1_AWID(read_attn_U0_m_axi_inout1_AWID),
    .m_axi_inout1_AWLEN(read_attn_U0_m_axi_inout1_AWLEN),
    .m_axi_inout1_AWSIZE(read_attn_U0_m_axi_inout1_AWSIZE),
    .m_axi_inout1_AWBURST(read_attn_U0_m_axi_inout1_AWBURST),
    .m_axi_inout1_AWLOCK(read_attn_U0_m_axi_inout1_AWLOCK),
    .m_axi_inout1_AWCACHE(read_attn_U0_m_axi_inout1_AWCACHE),
    .m_axi_inout1_AWPROT(read_attn_U0_m_axi_inout1_AWPROT),
    .m_axi_inout1_AWQOS(read_attn_U0_m_axi_inout1_AWQOS),
    .m_axi_inout1_AWREGION(read_attn_U0_m_axi_inout1_AWREGION),
    .m_axi_inout1_AWUSER(read_attn_U0_m_axi_inout1_AWUSER),
    .m_axi_inout1_WVALID(read_attn_U0_m_axi_inout1_WVALID),
    .m_axi_inout1_WREADY(1'b0),
    .m_axi_inout1_WDATA(read_attn_U0_m_axi_inout1_WDATA),
    .m_axi_inout1_WSTRB(read_attn_U0_m_axi_inout1_WSTRB),
    .m_axi_inout1_WLAST(read_attn_U0_m_axi_inout1_WLAST),
    .m_axi_inout1_WID(read_attn_U0_m_axi_inout1_WID),
    .m_axi_inout1_WUSER(read_attn_U0_m_axi_inout1_WUSER),
    .m_axi_inout1_ARVALID(read_attn_U0_m_axi_inout1_ARVALID),
    .m_axi_inout1_ARREADY(m_axi_inout1_ARREADY),
    .m_axi_inout1_ARADDR(read_attn_U0_m_axi_inout1_ARADDR),
    .m_axi_inout1_ARID(read_attn_U0_m_axi_inout1_ARID),
    .m_axi_inout1_ARLEN(read_attn_U0_m_axi_inout1_ARLEN),
    .m_axi_inout1_ARSIZE(read_attn_U0_m_axi_inout1_ARSIZE),
    .m_axi_inout1_ARBURST(read_attn_U0_m_axi_inout1_ARBURST),
    .m_axi_inout1_ARLOCK(read_attn_U0_m_axi_inout1_ARLOCK),
    .m_axi_inout1_ARCACHE(read_attn_U0_m_axi_inout1_ARCACHE),
    .m_axi_inout1_ARPROT(read_attn_U0_m_axi_inout1_ARPROT),
    .m_axi_inout1_ARQOS(read_attn_U0_m_axi_inout1_ARQOS),
    .m_axi_inout1_ARREGION(read_attn_U0_m_axi_inout1_ARREGION),
    .m_axi_inout1_ARUSER(read_attn_U0_m_axi_inout1_ARUSER),
    .m_axi_inout1_RVALID(m_axi_inout1_RVALID),
    .m_axi_inout1_RREADY(read_attn_U0_m_axi_inout1_RREADY),
    .m_axi_inout1_RDATA(m_axi_inout1_RDATA),
    .m_axi_inout1_RLAST(m_axi_inout1_RLAST),
    .m_axi_inout1_RID(m_axi_inout1_RID),
    .m_axi_inout1_RFIFONUM(m_axi_inout1_RFIFONUM),
    .m_axi_inout1_RUSER(m_axi_inout1_RUSER),
    .m_axi_inout1_RRESP(m_axi_inout1_RRESP),
    .m_axi_inout1_BVALID(1'b0),
    .m_axi_inout1_BREADY(read_attn_U0_m_axi_inout1_BREADY),
    .m_axi_inout1_BRESP(2'd0),
    .m_axi_inout1_BID(1'd0),
    .m_axi_inout1_BUSER(1'd0),
    .attn_stream_din(read_attn_U0_attn_stream_din),
    .attn_stream_num_data_valid(attn_stream_num_data_valid),
    .attn_stream_fifo_cap(attn_stream_fifo_cap),
    .attn_stream_full_n(attn_stream_full_n),
    .attn_stream_write(read_attn_U0_attn_stream_write),
    .start_out(read_attn_U0_start_out),
    .start_write(read_attn_U0_start_write),
    .attn(attn)
);

ViT_act_read_attn_softmax_info read_attn_softmax_info_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_attn_softmax_info_U0_ap_start),
    .ap_done(read_attn_softmax_info_U0_ap_done),
    .ap_continue(read_attn_softmax_info_U0_ap_continue),
    .ap_idle(read_attn_softmax_info_U0_ap_idle),
    .ap_ready(read_attn_softmax_info_U0_ap_ready),
    .attn_softmax_info_stream_din(read_attn_softmax_info_U0_attn_softmax_info_stream_din),
    .attn_softmax_info_stream_num_data_valid(attn_softmax_info_stream_num_data_valid),
    .attn_softmax_info_stream_fifo_cap(attn_softmax_info_stream_fifo_cap),
    .attn_softmax_info_stream_full_n(attn_softmax_info_stream_full_n),
    .attn_softmax_info_stream_write(read_attn_softmax_info_U0_attn_softmax_info_stream_write),
    .m_axi_inout4_AWVALID(read_attn_softmax_info_U0_m_axi_inout4_AWVALID),
    .m_axi_inout4_AWREADY(1'b0),
    .m_axi_inout4_AWADDR(read_attn_softmax_info_U0_m_axi_inout4_AWADDR),
    .m_axi_inout4_AWID(read_attn_softmax_info_U0_m_axi_inout4_AWID),
    .m_axi_inout4_AWLEN(read_attn_softmax_info_U0_m_axi_inout4_AWLEN),
    .m_axi_inout4_AWSIZE(read_attn_softmax_info_U0_m_axi_inout4_AWSIZE),
    .m_axi_inout4_AWBURST(read_attn_softmax_info_U0_m_axi_inout4_AWBURST),
    .m_axi_inout4_AWLOCK(read_attn_softmax_info_U0_m_axi_inout4_AWLOCK),
    .m_axi_inout4_AWCACHE(read_attn_softmax_info_U0_m_axi_inout4_AWCACHE),
    .m_axi_inout4_AWPROT(read_attn_softmax_info_U0_m_axi_inout4_AWPROT),
    .m_axi_inout4_AWQOS(read_attn_softmax_info_U0_m_axi_inout4_AWQOS),
    .m_axi_inout4_AWREGION(read_attn_softmax_info_U0_m_axi_inout4_AWREGION),
    .m_axi_inout4_AWUSER(read_attn_softmax_info_U0_m_axi_inout4_AWUSER),
    .m_axi_inout4_WVALID(read_attn_softmax_info_U0_m_axi_inout4_WVALID),
    .m_axi_inout4_WREADY(1'b0),
    .m_axi_inout4_WDATA(read_attn_softmax_info_U0_m_axi_inout4_WDATA),
    .m_axi_inout4_WSTRB(read_attn_softmax_info_U0_m_axi_inout4_WSTRB),
    .m_axi_inout4_WLAST(read_attn_softmax_info_U0_m_axi_inout4_WLAST),
    .m_axi_inout4_WID(read_attn_softmax_info_U0_m_axi_inout4_WID),
    .m_axi_inout4_WUSER(read_attn_softmax_info_U0_m_axi_inout4_WUSER),
    .m_axi_inout4_ARVALID(read_attn_softmax_info_U0_m_axi_inout4_ARVALID),
    .m_axi_inout4_ARREADY(m_axi_inout4_ARREADY),
    .m_axi_inout4_ARADDR(read_attn_softmax_info_U0_m_axi_inout4_ARADDR),
    .m_axi_inout4_ARID(read_attn_softmax_info_U0_m_axi_inout4_ARID),
    .m_axi_inout4_ARLEN(read_attn_softmax_info_U0_m_axi_inout4_ARLEN),
    .m_axi_inout4_ARSIZE(read_attn_softmax_info_U0_m_axi_inout4_ARSIZE),
    .m_axi_inout4_ARBURST(read_attn_softmax_info_U0_m_axi_inout4_ARBURST),
    .m_axi_inout4_ARLOCK(read_attn_softmax_info_U0_m_axi_inout4_ARLOCK),
    .m_axi_inout4_ARCACHE(read_attn_softmax_info_U0_m_axi_inout4_ARCACHE),
    .m_axi_inout4_ARPROT(read_attn_softmax_info_U0_m_axi_inout4_ARPROT),
    .m_axi_inout4_ARQOS(read_attn_softmax_info_U0_m_axi_inout4_ARQOS),
    .m_axi_inout4_ARREGION(read_attn_softmax_info_U0_m_axi_inout4_ARREGION),
    .m_axi_inout4_ARUSER(read_attn_softmax_info_U0_m_axi_inout4_ARUSER),
    .m_axi_inout4_RVALID(m_axi_inout4_RVALID),
    .m_axi_inout4_RREADY(read_attn_softmax_info_U0_m_axi_inout4_RREADY),
    .m_axi_inout4_RDATA(m_axi_inout4_RDATA),
    .m_axi_inout4_RLAST(m_axi_inout4_RLAST),
    .m_axi_inout4_RID(m_axi_inout4_RID),
    .m_axi_inout4_RFIFONUM(m_axi_inout4_RFIFONUM),
    .m_axi_inout4_RUSER(m_axi_inout4_RUSER),
    .m_axi_inout4_RRESP(m_axi_inout4_RRESP),
    .m_axi_inout4_BVALID(1'b0),
    .m_axi_inout4_BREADY(read_attn_softmax_info_U0_m_axi_inout4_BREADY),
    .m_axi_inout4_BRESP(2'd0),
    .m_axi_inout4_BID(1'd0),
    .m_axi_inout4_BUSER(1'd0),
    .attn_softmax_info(attn_softmax_info)
);

ViT_act_prepare_attn prepare_attn_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(prepare_attn_U0_ap_start),
    .ap_done(prepare_attn_U0_ap_done),
    .ap_continue(prepare_attn_U0_ap_continue),
    .ap_idle(prepare_attn_U0_ap_idle),
    .ap_ready(prepare_attn_U0_ap_ready),
    .attn_stream_dout(attn_stream_dout),
    .attn_stream_num_data_valid(attn_stream_num_data_valid),
    .attn_stream_fifo_cap(attn_stream_fifo_cap),
    .attn_stream_empty_n(attn_stream_empty_n),
    .attn_stream_read(prepare_attn_U0_attn_stream_read),
    .qxk_out_stream_din(prepare_attn_U0_qxk_out_stream_din),
    .qxk_out_stream_num_data_valid(qxk_out_stream_num_data_valid),
    .qxk_out_stream_fifo_cap(qxk_out_stream_fifo_cap),
    .qxk_out_stream_full_n(qxk_out_stream_full_n),
    .qxk_out_stream_write(prepare_attn_U0_qxk_out_stream_write)
);

ViT_act_compute_attn_matmul_v_7 compute_attn_matmul_v_7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_attn_matmul_v_7_U0_ap_start),
    .ap_done(compute_attn_matmul_v_7_U0_ap_done),
    .ap_continue(compute_attn_matmul_v_7_U0_ap_continue),
    .ap_idle(compute_attn_matmul_v_7_U0_ap_idle),
    .ap_ready(compute_attn_matmul_v_7_U0_ap_ready),
    .attn_softmax_info_stream_dout(attn_softmax_info_stream_dout),
    .attn_softmax_info_stream_num_data_valid(attn_softmax_info_stream_num_data_valid),
    .attn_softmax_info_stream_fifo_cap(attn_softmax_info_stream_fifo_cap),
    .attn_softmax_info_stream_empty_n(attn_softmax_info_stream_empty_n),
    .attn_softmax_info_stream_read(compute_attn_matmul_v_7_U0_attn_softmax_info_stream_read),
    .qxk_out_stream_dout(qxk_out_stream_dout),
    .qxk_out_stream_num_data_valid(qxk_out_stream_num_data_valid),
    .qxk_out_stream_fifo_cap(qxk_out_stream_fifo_cap),
    .qxk_out_stream_empty_n(qxk_out_stream_empty_n),
    .qxk_out_stream_read(compute_attn_matmul_v_7_U0_qxk_out_stream_read),
    .v_stream_dout(v_stream_dout),
    .v_stream_num_data_valid(v_stream_num_data_valid),
    .v_stream_fifo_cap(v_stream_fifo_cap),
    .v_stream_empty_n(v_stream_empty_n),
    .v_stream_read(compute_attn_matmul_v_7_U0_v_stream_read),
    .attn_matmul_v_stream_din(compute_attn_matmul_v_7_U0_attn_matmul_v_stream_din),
    .attn_matmul_v_stream_num_data_valid(attn_matmul_v_stream_num_data_valid),
    .attn_matmul_v_stream_fifo_cap(attn_matmul_v_stream_fifo_cap),
    .attn_matmul_v_stream_full_n(attn_matmul_v_stream_full_n),
    .attn_matmul_v_stream_write(compute_attn_matmul_v_7_U0_attn_matmul_v_stream_write)
);

ViT_act_write_attn_matmul_v write_attn_matmul_v_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(write_attn_matmul_v_U0_ap_start),
    .ap_done(write_attn_matmul_v_U0_ap_done),
    .ap_continue(write_attn_matmul_v_U0_ap_continue),
    .ap_idle(write_attn_matmul_v_U0_ap_idle),
    .ap_ready(write_attn_matmul_v_U0_ap_ready),
    .m_axi_inout1_AWVALID(write_attn_matmul_v_U0_m_axi_inout1_AWVALID),
    .m_axi_inout1_AWREADY(m_axi_inout1_AWREADY),
    .m_axi_inout1_AWADDR(write_attn_matmul_v_U0_m_axi_inout1_AWADDR),
    .m_axi_inout1_AWID(write_attn_matmul_v_U0_m_axi_inout1_AWID),
    .m_axi_inout1_AWLEN(write_attn_matmul_v_U0_m_axi_inout1_AWLEN),
    .m_axi_inout1_AWSIZE(write_attn_matmul_v_U0_m_axi_inout1_AWSIZE),
    .m_axi_inout1_AWBURST(write_attn_matmul_v_U0_m_axi_inout1_AWBURST),
    .m_axi_inout1_AWLOCK(write_attn_matmul_v_U0_m_axi_inout1_AWLOCK),
    .m_axi_inout1_AWCACHE(write_attn_matmul_v_U0_m_axi_inout1_AWCACHE),
    .m_axi_inout1_AWPROT(write_attn_matmul_v_U0_m_axi_inout1_AWPROT),
    .m_axi_inout1_AWQOS(write_attn_matmul_v_U0_m_axi_inout1_AWQOS),
    .m_axi_inout1_AWREGION(write_attn_matmul_v_U0_m_axi_inout1_AWREGION),
    .m_axi_inout1_AWUSER(write_attn_matmul_v_U0_m_axi_inout1_AWUSER),
    .m_axi_inout1_WVALID(write_attn_matmul_v_U0_m_axi_inout1_WVALID),
    .m_axi_inout1_WREADY(m_axi_inout1_WREADY),
    .m_axi_inout1_WDATA(write_attn_matmul_v_U0_m_axi_inout1_WDATA),
    .m_axi_inout1_WSTRB(write_attn_matmul_v_U0_m_axi_inout1_WSTRB),
    .m_axi_inout1_WLAST(write_attn_matmul_v_U0_m_axi_inout1_WLAST),
    .m_axi_inout1_WID(write_attn_matmul_v_U0_m_axi_inout1_WID),
    .m_axi_inout1_WUSER(write_attn_matmul_v_U0_m_axi_inout1_WUSER),
    .m_axi_inout1_ARVALID(write_attn_matmul_v_U0_m_axi_inout1_ARVALID),
    .m_axi_inout1_ARREADY(1'b0),
    .m_axi_inout1_ARADDR(write_attn_matmul_v_U0_m_axi_inout1_ARADDR),
    .m_axi_inout1_ARID(write_attn_matmul_v_U0_m_axi_inout1_ARID),
    .m_axi_inout1_ARLEN(write_attn_matmul_v_U0_m_axi_inout1_ARLEN),
    .m_axi_inout1_ARSIZE(write_attn_matmul_v_U0_m_axi_inout1_ARSIZE),
    .m_axi_inout1_ARBURST(write_attn_matmul_v_U0_m_axi_inout1_ARBURST),
    .m_axi_inout1_ARLOCK(write_attn_matmul_v_U0_m_axi_inout1_ARLOCK),
    .m_axi_inout1_ARCACHE(write_attn_matmul_v_U0_m_axi_inout1_ARCACHE),
    .m_axi_inout1_ARPROT(write_attn_matmul_v_U0_m_axi_inout1_ARPROT),
    .m_axi_inout1_ARQOS(write_attn_matmul_v_U0_m_axi_inout1_ARQOS),
    .m_axi_inout1_ARREGION(write_attn_matmul_v_U0_m_axi_inout1_ARREGION),
    .m_axi_inout1_ARUSER(write_attn_matmul_v_U0_m_axi_inout1_ARUSER),
    .m_axi_inout1_RVALID(1'b0),
    .m_axi_inout1_RREADY(write_attn_matmul_v_U0_m_axi_inout1_RREADY),
    .m_axi_inout1_RDATA(256'd0),
    .m_axi_inout1_RLAST(1'b0),
    .m_axi_inout1_RID(1'd0),
    .m_axi_inout1_RFIFONUM(9'd0),
    .m_axi_inout1_RUSER(1'd0),
    .m_axi_inout1_RRESP(2'd0),
    .m_axi_inout1_BVALID(m_axi_inout1_BVALID),
    .m_axi_inout1_BREADY(write_attn_matmul_v_U0_m_axi_inout1_BREADY),
    .m_axi_inout1_BRESP(m_axi_inout1_BRESP),
    .m_axi_inout1_BID(m_axi_inout1_BID),
    .m_axi_inout1_BUSER(m_axi_inout1_BUSER),
    .attn_matmul_v_dout(attn_matmul_v_c_dout),
    .attn_matmul_v_num_data_valid(attn_matmul_v_c_num_data_valid),
    .attn_matmul_v_fifo_cap(attn_matmul_v_c_fifo_cap),
    .attn_matmul_v_empty_n(attn_matmul_v_c_empty_n),
    .attn_matmul_v_read(write_attn_matmul_v_U0_attn_matmul_v_read),
    .attn_matmul_v_stream_dout(attn_matmul_v_stream_dout),
    .attn_matmul_v_stream_num_data_valid(attn_matmul_v_stream_num_data_valid),
    .attn_matmul_v_stream_fifo_cap(attn_matmul_v_stream_fifo_cap),
    .attn_matmul_v_stream_empty_n(attn_matmul_v_stream_empty_n),
    .attn_matmul_v_stream_read(write_attn_matmul_v_U0_attn_matmul_v_stream_read)
);

ViT_act_fifo_w64_d5_S_x attn_matmul_v_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc25_U0_attn_matmul_v_c_din),
    .if_full_n(attn_matmul_v_c_full_n),
    .if_write(entry_proc25_U0_attn_matmul_v_c_write),
    .if_dout(attn_matmul_v_c_dout),
    .if_num_data_valid(attn_matmul_v_c_num_data_valid),
    .if_fifo_cap(attn_matmul_v_c_fifo_cap),
    .if_empty_n(attn_matmul_v_c_empty_n),
    .if_read(write_attn_matmul_v_U0_attn_matmul_v_read)
);

ViT_act_fifo_w256_d2_S_x0 v_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_k_v_6_U0_v_stream_din),
    .if_full_n(v_stream_full_n),
    .if_write(read_k_v_6_U0_v_stream_write),
    .if_dout(v_stream_dout),
    .if_num_data_valid(v_stream_num_data_valid),
    .if_fifo_cap(v_stream_fifo_cap),
    .if_empty_n(v_stream_empty_n),
    .if_read(compute_attn_matmul_v_7_U0_v_stream_read)
);

ViT_act_fifo_w128_d2_S_x attn_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_attn_U0_attn_stream_din),
    .if_full_n(attn_stream_full_n),
    .if_write(read_attn_U0_attn_stream_write),
    .if_dout(attn_stream_dout),
    .if_num_data_valid(attn_stream_num_data_valid),
    .if_fifo_cap(attn_stream_fifo_cap),
    .if_empty_n(attn_stream_empty_n),
    .if_read(prepare_attn_U0_attn_stream_read)
);

ViT_act_fifo_w256_d2_S_x0 attn_softmax_info_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_attn_softmax_info_U0_attn_softmax_info_stream_din),
    .if_full_n(attn_softmax_info_stream_full_n),
    .if_write(read_attn_softmax_info_U0_attn_softmax_info_stream_write),
    .if_dout(attn_softmax_info_stream_dout),
    .if_num_data_valid(attn_softmax_info_stream_num_data_valid),
    .if_fifo_cap(attn_softmax_info_stream_fifo_cap),
    .if_empty_n(attn_softmax_info_stream_empty_n),
    .if_read(compute_attn_matmul_v_7_U0_attn_softmax_info_stream_read)
);

ViT_act_fifo_w512_d2_S_x0 qxk_out_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(prepare_attn_U0_qxk_out_stream_din),
    .if_full_n(qxk_out_stream_full_n),
    .if_write(prepare_attn_U0_qxk_out_stream_write),
    .if_dout(qxk_out_stream_dout),
    .if_num_data_valid(qxk_out_stream_num_data_valid),
    .if_fifo_cap(qxk_out_stream_fifo_cap),
    .if_empty_n(qxk_out_stream_empty_n),
    .if_read(compute_attn_matmul_v_7_U0_qxk_out_stream_read)
);

ViT_act_fifo_w256_d2_S_x0 attn_matmul_v_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_attn_matmul_v_7_U0_attn_matmul_v_stream_din),
    .if_full_n(attn_matmul_v_stream_full_n),
    .if_write(compute_attn_matmul_v_7_U0_attn_matmul_v_stream_write),
    .if_dout(attn_matmul_v_stream_dout),
    .if_num_data_valid(attn_matmul_v_stream_num_data_valid),
    .if_fifo_cap(attn_matmul_v_stream_fifo_cap),
    .if_empty_n(attn_matmul_v_stream_empty_n),
    .if_read(write_attn_matmul_v_U0_attn_matmul_v_stream_read)
);

ViT_act_start_for_write_attn_matmul_v_U0 start_for_write_attn_matmul_v_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_attn_matmul_v_U0_din),
    .if_full_n(start_for_write_attn_matmul_v_U0_full_n),
    .if_write(entry_proc25_U0_start_write),
    .if_dout(start_for_write_attn_matmul_v_U0_dout),
    .if_empty_n(start_for_write_attn_matmul_v_U0_empty_n),
    .if_read(write_attn_matmul_v_U0_ap_ready)
);

ViT_act_start_for_compute_attn_matmul_v_7_U0 start_for_compute_attn_matmul_v_7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_attn_matmul_v_7_U0_din),
    .if_full_n(start_for_compute_attn_matmul_v_7_U0_full_n),
    .if_write(read_k_v_6_U0_start_write),
    .if_dout(start_for_compute_attn_matmul_v_7_U0_dout),
    .if_empty_n(start_for_compute_attn_matmul_v_7_U0_empty_n),
    .if_read(compute_attn_matmul_v_7_U0_ap_ready)
);

ViT_act_start_for_prepare_attn_U0 start_for_prepare_attn_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_prepare_attn_U0_din),
    .if_full_n(start_for_prepare_attn_U0_full_n),
    .if_write(read_attn_U0_start_write),
    .if_dout(start_for_prepare_attn_U0_dout),
    .if_empty_n(start_for_prepare_attn_U0_empty_n),
    .if_read(prepare_attn_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc25_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc25_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc25_U0_ap_ready <= ap_sync_entry_proc25_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_read_attn_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_attn_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_attn_U0_ap_ready <= ap_sync_read_attn_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_read_attn_softmax_info_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_attn_softmax_info_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_attn_softmax_info_U0_ap_ready <= ap_sync_read_attn_softmax_info_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_read_k_v_6_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_k_v_6_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_k_v_6_U0_ap_ready <= ap_sync_read_k_v_6_U0_ap_ready;
        end
    end
end

assign ap_done = write_attn_matmul_v_U0_ap_done;

assign ap_idle = (write_attn_matmul_v_U0_ap_idle & read_k_v_6_U0_ap_idle & read_attn_softmax_info_U0_ap_idle & read_attn_U0_ap_idle & prepare_attn_U0_ap_idle & entry_proc25_U0_ap_idle & compute_attn_matmul_v_7_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_entry_proc25_U0_ap_ready = (entry_proc25_U0_ap_ready | ap_sync_reg_entry_proc25_U0_ap_ready);

assign ap_sync_read_attn_U0_ap_ready = (read_attn_U0_ap_ready | ap_sync_reg_read_attn_U0_ap_ready);

assign ap_sync_read_attn_softmax_info_U0_ap_ready = (read_attn_softmax_info_U0_ap_ready | ap_sync_reg_read_attn_softmax_info_U0_ap_ready);

assign ap_sync_read_k_v_6_U0_ap_ready = (read_k_v_6_U0_ap_ready | ap_sync_reg_read_k_v_6_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_k_v_6_U0_ap_ready & ap_sync_read_attn_softmax_info_U0_ap_ready & ap_sync_read_attn_U0_ap_ready & ap_sync_entry_proc25_U0_ap_ready);

assign compute_attn_matmul_v_7_U0_ap_continue = 1'b1;

assign compute_attn_matmul_v_7_U0_ap_start = start_for_compute_attn_matmul_v_7_U0_empty_n;

assign entry_proc25_U0_ap_continue = 1'b1;

assign entry_proc25_U0_ap_start = ((ap_sync_reg_entry_proc25_U0_ap_ready ^ 1'b1) & ap_start);

assign m_axi_inout1_ARADDR = read_attn_U0_m_axi_inout1_ARADDR;

assign m_axi_inout1_ARBURST = read_attn_U0_m_axi_inout1_ARBURST;

assign m_axi_inout1_ARCACHE = read_attn_U0_m_axi_inout1_ARCACHE;

assign m_axi_inout1_ARID = read_attn_U0_m_axi_inout1_ARID;

assign m_axi_inout1_ARLEN = read_attn_U0_m_axi_inout1_ARLEN;

assign m_axi_inout1_ARLOCK = read_attn_U0_m_axi_inout1_ARLOCK;

assign m_axi_inout1_ARPROT = read_attn_U0_m_axi_inout1_ARPROT;

assign m_axi_inout1_ARQOS = read_attn_U0_m_axi_inout1_ARQOS;

assign m_axi_inout1_ARREGION = read_attn_U0_m_axi_inout1_ARREGION;

assign m_axi_inout1_ARSIZE = read_attn_U0_m_axi_inout1_ARSIZE;

assign m_axi_inout1_ARUSER = read_attn_U0_m_axi_inout1_ARUSER;

assign m_axi_inout1_ARVALID = read_attn_U0_m_axi_inout1_ARVALID;

assign m_axi_inout1_AWADDR = write_attn_matmul_v_U0_m_axi_inout1_AWADDR;

assign m_axi_inout1_AWBURST = write_attn_matmul_v_U0_m_axi_inout1_AWBURST;

assign m_axi_inout1_AWCACHE = write_attn_matmul_v_U0_m_axi_inout1_AWCACHE;

assign m_axi_inout1_AWID = write_attn_matmul_v_U0_m_axi_inout1_AWID;

assign m_axi_inout1_AWLEN = write_attn_matmul_v_U0_m_axi_inout1_AWLEN;

assign m_axi_inout1_AWLOCK = write_attn_matmul_v_U0_m_axi_inout1_AWLOCK;

assign m_axi_inout1_AWPROT = write_attn_matmul_v_U0_m_axi_inout1_AWPROT;

assign m_axi_inout1_AWQOS = write_attn_matmul_v_U0_m_axi_inout1_AWQOS;

assign m_axi_inout1_AWREGION = write_attn_matmul_v_U0_m_axi_inout1_AWREGION;

assign m_axi_inout1_AWSIZE = write_attn_matmul_v_U0_m_axi_inout1_AWSIZE;

assign m_axi_inout1_AWUSER = write_attn_matmul_v_U0_m_axi_inout1_AWUSER;

assign m_axi_inout1_AWVALID = write_attn_matmul_v_U0_m_axi_inout1_AWVALID;

assign m_axi_inout1_BREADY = write_attn_matmul_v_U0_m_axi_inout1_BREADY;

assign m_axi_inout1_RREADY = read_attn_U0_m_axi_inout1_RREADY;

assign m_axi_inout1_WDATA = write_attn_matmul_v_U0_m_axi_inout1_WDATA;

assign m_axi_inout1_WID = write_attn_matmul_v_U0_m_axi_inout1_WID;

assign m_axi_inout1_WLAST = write_attn_matmul_v_U0_m_axi_inout1_WLAST;

assign m_axi_inout1_WSTRB = write_attn_matmul_v_U0_m_axi_inout1_WSTRB;

assign m_axi_inout1_WUSER = write_attn_matmul_v_U0_m_axi_inout1_WUSER;

assign m_axi_inout1_WVALID = write_attn_matmul_v_U0_m_axi_inout1_WVALID;

assign m_axi_inout2_ARADDR = read_k_v_6_U0_m_axi_inout2_ARADDR;

assign m_axi_inout2_ARBURST = read_k_v_6_U0_m_axi_inout2_ARBURST;

assign m_axi_inout2_ARCACHE = read_k_v_6_U0_m_axi_inout2_ARCACHE;

assign m_axi_inout2_ARID = read_k_v_6_U0_m_axi_inout2_ARID;

assign m_axi_inout2_ARLEN = read_k_v_6_U0_m_axi_inout2_ARLEN;

assign m_axi_inout2_ARLOCK = read_k_v_6_U0_m_axi_inout2_ARLOCK;

assign m_axi_inout2_ARPROT = read_k_v_6_U0_m_axi_inout2_ARPROT;

assign m_axi_inout2_ARQOS = read_k_v_6_U0_m_axi_inout2_ARQOS;

assign m_axi_inout2_ARREGION = read_k_v_6_U0_m_axi_inout2_ARREGION;

assign m_axi_inout2_ARSIZE = read_k_v_6_U0_m_axi_inout2_ARSIZE;

assign m_axi_inout2_ARUSER = read_k_v_6_U0_m_axi_inout2_ARUSER;

assign m_axi_inout2_ARVALID = read_k_v_6_U0_m_axi_inout2_ARVALID;

assign m_axi_inout2_AWADDR = 64'd0;

assign m_axi_inout2_AWBURST = 2'd0;

assign m_axi_inout2_AWCACHE = 4'd0;

assign m_axi_inout2_AWID = 1'd0;

assign m_axi_inout2_AWLEN = 32'd0;

assign m_axi_inout2_AWLOCK = 2'd0;

assign m_axi_inout2_AWPROT = 3'd0;

assign m_axi_inout2_AWQOS = 4'd0;

assign m_axi_inout2_AWREGION = 4'd0;

assign m_axi_inout2_AWSIZE = 3'd0;

assign m_axi_inout2_AWUSER = 1'd0;

assign m_axi_inout2_AWVALID = 1'b0;

assign m_axi_inout2_BREADY = 1'b0;

assign m_axi_inout2_RREADY = read_k_v_6_U0_m_axi_inout2_RREADY;

assign m_axi_inout2_WDATA = 256'd0;

assign m_axi_inout2_WID = 1'd0;

assign m_axi_inout2_WLAST = 1'b0;

assign m_axi_inout2_WSTRB = 32'd0;

assign m_axi_inout2_WUSER = 1'd0;

assign m_axi_inout2_WVALID = 1'b0;

assign m_axi_inout4_ARADDR = read_attn_softmax_info_U0_m_axi_inout4_ARADDR;

assign m_axi_inout4_ARBURST = read_attn_softmax_info_U0_m_axi_inout4_ARBURST;

assign m_axi_inout4_ARCACHE = read_attn_softmax_info_U0_m_axi_inout4_ARCACHE;

assign m_axi_inout4_ARID = read_attn_softmax_info_U0_m_axi_inout4_ARID;

assign m_axi_inout4_ARLEN = read_attn_softmax_info_U0_m_axi_inout4_ARLEN;

assign m_axi_inout4_ARLOCK = read_attn_softmax_info_U0_m_axi_inout4_ARLOCK;

assign m_axi_inout4_ARPROT = read_attn_softmax_info_U0_m_axi_inout4_ARPROT;

assign m_axi_inout4_ARQOS = read_attn_softmax_info_U0_m_axi_inout4_ARQOS;

assign m_axi_inout4_ARREGION = read_attn_softmax_info_U0_m_axi_inout4_ARREGION;

assign m_axi_inout4_ARSIZE = read_attn_softmax_info_U0_m_axi_inout4_ARSIZE;

assign m_axi_inout4_ARUSER = read_attn_softmax_info_U0_m_axi_inout4_ARUSER;

assign m_axi_inout4_ARVALID = read_attn_softmax_info_U0_m_axi_inout4_ARVALID;

assign m_axi_inout4_AWADDR = 64'd0;

assign m_axi_inout4_AWBURST = 2'd0;

assign m_axi_inout4_AWCACHE = 4'd0;

assign m_axi_inout4_AWID = 1'd0;

assign m_axi_inout4_AWLEN = 32'd0;

assign m_axi_inout4_AWLOCK = 2'd0;

assign m_axi_inout4_AWPROT = 3'd0;

assign m_axi_inout4_AWQOS = 4'd0;

assign m_axi_inout4_AWREGION = 4'd0;

assign m_axi_inout4_AWSIZE = 3'd0;

assign m_axi_inout4_AWUSER = 1'd0;

assign m_axi_inout4_AWVALID = 1'b0;

assign m_axi_inout4_BREADY = 1'b0;

assign m_axi_inout4_RREADY = read_attn_softmax_info_U0_m_axi_inout4_RREADY;

assign m_axi_inout4_WDATA = 256'd0;

assign m_axi_inout4_WID = 1'd0;

assign m_axi_inout4_WLAST = 1'b0;

assign m_axi_inout4_WSTRB = 32'd0;

assign m_axi_inout4_WUSER = 1'd0;

assign m_axi_inout4_WVALID = 1'b0;

assign prepare_attn_U0_ap_continue = 1'b1;

assign prepare_attn_U0_ap_start = start_for_prepare_attn_U0_empty_n;

assign read_attn_U0_ap_continue = 1'b1;

assign read_attn_U0_ap_start = ((ap_sync_reg_read_attn_U0_ap_ready ^ 1'b1) & ap_start);

assign read_attn_softmax_info_U0_ap_continue = 1'b1;

assign read_attn_softmax_info_U0_ap_start = ((ap_sync_reg_read_attn_softmax_info_U0_ap_ready ^ 1'b1) & ap_start);

assign read_k_v_6_U0_ap_continue = 1'b1;

assign read_k_v_6_U0_ap_start = ((ap_sync_reg_read_k_v_6_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_compute_attn_matmul_v_7_U0_din = 1'b1;

assign start_for_prepare_attn_U0_din = 1'b1;

assign start_for_write_attn_matmul_v_U0_din = 1'b1;

assign write_attn_matmul_v_U0_ap_continue = ap_continue;

assign write_attn_matmul_v_U0_ap_start = start_for_write_attn_matmul_v_U0_empty_n;

endmodule //ViT_act_compute_attn_matmul_v
