-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_act_write_out_stream_direct_Pipeline_ln231_for_each_i is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    out_stream_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    out_stream_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    out_stream_empty_n : IN STD_LOGIC;
    out_stream_read : OUT STD_LOGIC;
    m_axi_inout2_AWVALID : OUT STD_LOGIC;
    m_axi_inout2_AWREADY : IN STD_LOGIC;
    m_axi_inout2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_WVALID : OUT STD_LOGIC;
    m_axi_inout2_WREADY : IN STD_LOGIC;
    m_axi_inout2_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout2_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout2_WLAST : OUT STD_LOGIC;
    m_axi_inout2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_ARVALID : OUT STD_LOGIC;
    m_axi_inout2_ARREADY : IN STD_LOGIC;
    m_axi_inout2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_inout2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_inout2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_inout2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_inout2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_RVALID : IN STD_LOGIC;
    m_axi_inout2_RREADY : OUT STD_LOGIC;
    m_axi_inout2_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_inout2_RLAST : IN STD_LOGIC;
    m_axi_inout2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_inout2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_BVALID : IN STD_LOGIC;
    m_axi_inout2_BREADY : OUT STD_LOGIC;
    m_axi_inout2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_inout2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_inout2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln231 : IN STD_LOGIC_VECTOR (58 downto 0);
    iters : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of ViT_act_write_out_stream_direct_Pipeline_ln231_for_each_i is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln231_reg_783 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln238_reg_787 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op49_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln231_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal inout2_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln231_reg_783_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln238_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln255_fu_277_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln255_reg_791 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln255_reg_791_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_i_fu_578_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_i_reg_808 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_i_fu_587_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_i_reg_813 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_i_fu_596_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_i_reg_818 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_i_fu_605_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_i_reg_823 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_i_fu_614_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_i_reg_828 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_i_fu_623_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_i_reg_833 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_i_fu_632_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_i_reg_838 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_i_fu_641_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_i_reg_843 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal block_fu_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal next_block_fu_263_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_126 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln231_fu_245_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_0_0_0_0_031_i_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln243_fu_291_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_1_0_0_043_i_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_2_0_0_055_i_fu_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_3_0_0_067_i_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_4_0_0_079_i_fu_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_5_0_0_0811_i_fu_150 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_6_0_0_0913_i_fu_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_7_0_0_01015_i_fu_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_8_0_0_017_i_fu_162 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_9_0_0_019_i_fu_166 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_10_0_0_021_i_fu_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_11_0_0_023_i_fu_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_12_0_0_025_i_fu_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_13_0_0_027_i_fu_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_14_0_0_029_i_fu_186 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_15_0_0_031_i_fu_190 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln236_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln236_fu_257_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_act_mux_21_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ViT_act_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_21_32_1_1_U806 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_0_0_0_031_i_fu_130,
        din1 => p_0_0_8_0_0_017_i_fu_162,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_14_i_fu_578_p4);

    mux_21_32_1_1_U807 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_1_0_0_043_i_fu_134,
        din1 => p_0_0_9_0_0_019_i_fu_166,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_15_i_fu_587_p4);

    mux_21_32_1_1_U808 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_2_0_0_055_i_fu_138,
        din1 => p_0_0_10_0_0_021_i_fu_170,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_16_i_fu_596_p4);

    mux_21_32_1_1_U809 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_3_0_0_067_i_fu_142,
        din1 => p_0_0_11_0_0_023_i_fu_174,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_17_i_fu_605_p4);

    mux_21_32_1_1_U810 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_4_0_0_079_i_fu_146,
        din1 => p_0_0_12_0_0_025_i_fu_178,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_18_i_fu_614_p4);

    mux_21_32_1_1_U811 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_5_0_0_0811_i_fu_150,
        din1 => p_0_0_13_0_0_027_i_fu_182,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_19_i_fu_623_p4);

    mux_21_32_1_1_U812 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_6_0_0_0913_i_fu_154,
        din1 => p_0_0_14_0_0_029_i_fu_186,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_20_i_fu_632_p4);

    mux_21_32_1_1_U813 : component ViT_act_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => p_0_0_7_0_0_01015_i_fu_158,
        din1 => p_0_0_15_0_0_031_i_fu_190,
        din2 => trunc_ln255_reg_791_pp0_iter2_reg,
        dout => tmp_21_i_fu_641_p4);

    flow_control_loop_pipe_sequential_init_U : component ViT_act_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    block_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    block_fu_122 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln231_fu_240_p2 = ap_const_lv1_0))) then 
                    block_fu_122 <= next_block_fu_263_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_126 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln231_fu_240_p2 = ap_const_lv1_0))) then 
                    i_fu_126 <= add_ln231_fu_245_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln231_reg_783 <= icmp_ln231_fu_240_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln231_reg_783_pp0_iter2_reg <= icmp_ln231_reg_783;
                trunc_ln255_reg_791_pp0_iter2_reg <= trunc_ln255_reg_791;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln231_fu_240_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln238_reg_787 <= icmp_ln238_fu_271_p2;
                trunc_ln255_reg_791 <= trunc_ln255_fu_277_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln238_reg_787 = ap_const_lv1_1) and (icmp_ln231_reg_783 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_0_0_0_0_0_031_i_fu_130 <= trunc_ln243_fu_291_p1;
                p_0_0_10_0_0_021_i_fu_170 <= out_stream_dout(351 downto 320);
                p_0_0_11_0_0_023_i_fu_174 <= out_stream_dout(383 downto 352);
                p_0_0_12_0_0_025_i_fu_178 <= out_stream_dout(415 downto 384);
                p_0_0_13_0_0_027_i_fu_182 <= out_stream_dout(447 downto 416);
                p_0_0_14_0_0_029_i_fu_186 <= out_stream_dout(479 downto 448);
                p_0_0_15_0_0_031_i_fu_190 <= out_stream_dout(511 downto 480);
                p_0_0_1_0_0_043_i_fu_134 <= out_stream_dout(63 downto 32);
                p_0_0_2_0_0_055_i_fu_138 <= out_stream_dout(95 downto 64);
                p_0_0_3_0_0_067_i_fu_142 <= out_stream_dout(127 downto 96);
                p_0_0_4_0_0_079_i_fu_146 <= out_stream_dout(159 downto 128);
                p_0_0_5_0_0_0811_i_fu_150 <= out_stream_dout(191 downto 160);
                p_0_0_6_0_0_0913_i_fu_154 <= out_stream_dout(223 downto 192);
                p_0_0_7_0_0_01015_i_fu_158 <= out_stream_dout(255 downto 224);
                p_0_0_8_0_0_017_i_fu_162 <= out_stream_dout(287 downto 256);
                p_0_0_9_0_0_019_i_fu_166 <= out_stream_dout(319 downto 288);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln231_reg_783_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_14_i_reg_808 <= tmp_14_i_fu_578_p4;
                tmp_15_i_reg_813 <= tmp_15_i_fu_587_p4;
                tmp_16_i_reg_818 <= tmp_16_i_fu_596_p4;
                tmp_17_i_reg_823 <= tmp_17_i_fu_605_p4;
                tmp_18_i_reg_828 <= tmp_18_i_fu_614_p4;
                tmp_19_i_reg_833 <= tmp_19_i_fu_623_p4;
                tmp_20_i_reg_838 <= tmp_20_i_fu_632_p4;
                tmp_21_i_reg_843 <= tmp_21_i_fu_641_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln231_fu_245_p2 <= std_logic_vector(unsigned(i_fu_126) + unsigned(ap_const_lv16_1));
    add_ln236_fu_257_p2 <= std_logic_vector(unsigned(block_fu_122) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, out_stream_empty_n, ap_predicate_op49_read_state3)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (out_stream_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, out_stream_empty_n, ap_predicate_op49_read_state3, m_axi_inout2_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (out_stream_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((m_axi_inout2_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, out_stream_empty_n, ap_predicate_op49_read_state3, m_axi_inout2_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (out_stream_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((m_axi_inout2_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(out_stream_empty_n, ap_predicate_op49_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (out_stream_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln231_fu_240_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln231_fu_240_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln231_reg_783_pp0_iter2_reg)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln231_reg_783_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_predicate_op49_read_state3_assign_proc : process(icmp_ln231_reg_783, icmp_ln238_reg_787)
    begin
                ap_predicate_op49_read_state3 <= ((icmp_ln238_reg_787 = ap_const_lv1_1) and (icmp_ln231_reg_783 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln231_fu_240_p2 <= "1" when (i_fu_126 = iters) else "0";
    icmp_ln236_fu_251_p2 <= "1" when (block_fu_122 = ap_const_lv32_1) else "0";
    icmp_ln238_fu_271_p2 <= "1" when (block_fu_122 = ap_const_lv32_0) else "0";

    inout2_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_inout2_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            inout2_blk_n_W <= m_axi_inout2_WREADY;
        else 
            inout2_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    m_axi_inout2_ARADDR <= ap_const_lv64_0;
    m_axi_inout2_ARBURST <= ap_const_lv2_0;
    m_axi_inout2_ARCACHE <= ap_const_lv4_0;
    m_axi_inout2_ARID <= ap_const_lv1_0;
    m_axi_inout2_ARLEN <= ap_const_lv32_0;
    m_axi_inout2_ARLOCK <= ap_const_lv2_0;
    m_axi_inout2_ARPROT <= ap_const_lv3_0;
    m_axi_inout2_ARQOS <= ap_const_lv4_0;
    m_axi_inout2_ARREGION <= ap_const_lv4_0;
    m_axi_inout2_ARSIZE <= ap_const_lv3_0;
    m_axi_inout2_ARUSER <= ap_const_lv1_0;
    m_axi_inout2_ARVALID <= ap_const_logic_0;
    m_axi_inout2_AWADDR <= ap_const_lv64_0;
    m_axi_inout2_AWBURST <= ap_const_lv2_0;
    m_axi_inout2_AWCACHE <= ap_const_lv4_0;
    m_axi_inout2_AWID <= ap_const_lv1_0;
    m_axi_inout2_AWLEN <= ap_const_lv32_0;
    m_axi_inout2_AWLOCK <= ap_const_lv2_0;
    m_axi_inout2_AWPROT <= ap_const_lv3_0;
    m_axi_inout2_AWQOS <= ap_const_lv4_0;
    m_axi_inout2_AWREGION <= ap_const_lv4_0;
    m_axi_inout2_AWSIZE <= ap_const_lv3_0;
    m_axi_inout2_AWUSER <= ap_const_lv1_0;
    m_axi_inout2_AWVALID <= ap_const_logic_0;
    m_axi_inout2_BREADY <= ap_const_logic_0;
    m_axi_inout2_RREADY <= ap_const_logic_0;
    m_axi_inout2_WDATA <= (((((((tmp_21_i_reg_843 & tmp_20_i_reg_838) & tmp_19_i_reg_833) & tmp_18_i_reg_828) & tmp_17_i_reg_823) & tmp_16_i_reg_818) & tmp_15_i_reg_813) & tmp_14_i_reg_808);
    m_axi_inout2_WID <= ap_const_lv1_0;
    m_axi_inout2_WLAST <= ap_const_logic_0;
    m_axi_inout2_WSTRB <= ap_const_lv32_FFFFFFFF;
    m_axi_inout2_WUSER <= ap_const_lv1_0;

    m_axi_inout2_WVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_inout2_WVALID <= ap_const_logic_1;
        else 
            m_axi_inout2_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    next_block_fu_263_p3 <= 
        ap_const_lv32_0 when (icmp_ln236_fu_251_p2(0) = '1') else 
        add_ln236_fu_257_p2;

    out_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, out_stream_empty_n, ap_predicate_op49_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            out_stream_blk_n <= out_stream_empty_n;
        else 
            out_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_stream_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op49_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op49_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_stream_read <= ap_const_logic_1;
        else 
            out_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln243_fu_291_p1 <= out_stream_dout(32 - 1 downto 0);
    trunc_ln255_fu_277_p1 <= block_fu_122(1 - 1 downto 0);
end behav;
