// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ViT_act_write_attn_Pipeline_ln245_for_each_q_patch_block_ln247_for_each_k_patch_ln249 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        attn_stream_dout,
        attn_stream_num_data_valid,
        attn_stream_fifo_cap,
        attn_stream_empty_n,
        attn_stream_read,
        m_axi_inout1_AWVALID,
        m_axi_inout1_AWREADY,
        m_axi_inout1_AWADDR,
        m_axi_inout1_AWID,
        m_axi_inout1_AWLEN,
        m_axi_inout1_AWSIZE,
        m_axi_inout1_AWBURST,
        m_axi_inout1_AWLOCK,
        m_axi_inout1_AWCACHE,
        m_axi_inout1_AWPROT,
        m_axi_inout1_AWQOS,
        m_axi_inout1_AWREGION,
        m_axi_inout1_AWUSER,
        m_axi_inout1_WVALID,
        m_axi_inout1_WREADY,
        m_axi_inout1_WDATA,
        m_axi_inout1_WSTRB,
        m_axi_inout1_WLAST,
        m_axi_inout1_WID,
        m_axi_inout1_WUSER,
        m_axi_inout1_ARVALID,
        m_axi_inout1_ARREADY,
        m_axi_inout1_ARADDR,
        m_axi_inout1_ARID,
        m_axi_inout1_ARLEN,
        m_axi_inout1_ARSIZE,
        m_axi_inout1_ARBURST,
        m_axi_inout1_ARLOCK,
        m_axi_inout1_ARCACHE,
        m_axi_inout1_ARPROT,
        m_axi_inout1_ARQOS,
        m_axi_inout1_ARREGION,
        m_axi_inout1_ARUSER,
        m_axi_inout1_RVALID,
        m_axi_inout1_RREADY,
        m_axi_inout1_RDATA,
        m_axi_inout1_RLAST,
        m_axi_inout1_RID,
        m_axi_inout1_RFIFONUM,
        m_axi_inout1_RUSER,
        m_axi_inout1_RRESP,
        m_axi_inout1_BVALID,
        m_axi_inout1_BREADY,
        m_axi_inout1_BRESP,
        m_axi_inout1_BID,
        m_axi_inout1_BUSER,
        attn_load,
        trunc_ln252_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] attn_stream_dout;
input  [1:0] attn_stream_num_data_valid;
input  [1:0] attn_stream_fifo_cap;
input   attn_stream_empty_n;
output   attn_stream_read;
output   m_axi_inout1_AWVALID;
input   m_axi_inout1_AWREADY;
output  [63:0] m_axi_inout1_AWADDR;
output  [0:0] m_axi_inout1_AWID;
output  [31:0] m_axi_inout1_AWLEN;
output  [2:0] m_axi_inout1_AWSIZE;
output  [1:0] m_axi_inout1_AWBURST;
output  [1:0] m_axi_inout1_AWLOCK;
output  [3:0] m_axi_inout1_AWCACHE;
output  [2:0] m_axi_inout1_AWPROT;
output  [3:0] m_axi_inout1_AWQOS;
output  [3:0] m_axi_inout1_AWREGION;
output  [0:0] m_axi_inout1_AWUSER;
output   m_axi_inout1_WVALID;
input   m_axi_inout1_WREADY;
output  [255:0] m_axi_inout1_WDATA;
output  [31:0] m_axi_inout1_WSTRB;
output   m_axi_inout1_WLAST;
output  [0:0] m_axi_inout1_WID;
output  [0:0] m_axi_inout1_WUSER;
output   m_axi_inout1_ARVALID;
input   m_axi_inout1_ARREADY;
output  [63:0] m_axi_inout1_ARADDR;
output  [0:0] m_axi_inout1_ARID;
output  [31:0] m_axi_inout1_ARLEN;
output  [2:0] m_axi_inout1_ARSIZE;
output  [1:0] m_axi_inout1_ARBURST;
output  [1:0] m_axi_inout1_ARLOCK;
output  [3:0] m_axi_inout1_ARCACHE;
output  [2:0] m_axi_inout1_ARPROT;
output  [3:0] m_axi_inout1_ARQOS;
output  [3:0] m_axi_inout1_ARREGION;
output  [0:0] m_axi_inout1_ARUSER;
input   m_axi_inout1_RVALID;
output   m_axi_inout1_RREADY;
input  [255:0] m_axi_inout1_RDATA;
input   m_axi_inout1_RLAST;
input  [0:0] m_axi_inout1_RID;
input  [8:0] m_axi_inout1_RFIFONUM;
input  [0:0] m_axi_inout1_RUSER;
input  [1:0] m_axi_inout1_RRESP;
input   m_axi_inout1_BVALID;
output   m_axi_inout1_BREADY;
input  [1:0] m_axi_inout1_BRESP;
input  [0:0] m_axi_inout1_BID;
input  [0:0] m_axi_inout1_BUSER;
input  [63:0] attn_load;
input  [4:0] trunc_ln252_1;

reg ap_idle;
reg attn_stream_read;
reg m_axi_inout1_AWVALID;
reg m_axi_inout1_WVALID;
reg m_axi_inout1_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln245_fu_231_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    attn_stream_blk_n;
wire    ap_block_pp0_stage0;
reg    inout1_blk_n_AW;
reg    inout1_blk_n_W;
reg    inout1_blk_n_B;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln252_2_fu_425_p1;
reg   [0:0] trunc_ln252_2_reg_592;
reg   [58:0] trunc_ln252_8_reg_597;
wire   [31:0] shl_ln252_fu_509_p2;
reg   [31:0] shl_ln252_reg_602;
wire   [255:0] shl_ln252_1_fu_527_p2;
reg   [255:0] shl_ln252_1_reg_607;
wire  signed [63:0] sext_ln252_fu_533_p1;
reg    ap_block_pp0_stage0_01001;
reg   [2:0] q_patch_offset_fu_114;
wire   [2:0] add_ln249_fu_444_p2;
wire    ap_loop_init;
reg   [7:0] k_patch_fu_118;
wire   [7:0] select_ln247_1_fu_353_p3;
reg   [10:0] indvar_flatten_fu_122;
wire   [10:0] select_ln247_3_fu_456_p3;
reg   [5:0] q_patch_block_fu_126;
wire   [5:0] select_ln245_2_fu_307_p3;
reg   [14:0] indvar_flatten19_fu_130;
wire   [14:0] add_ln245_1_fu_237_p2;
wire   [9:0] shl_ln_fu_213_p3;
wire   [14:0] or_ln_fu_201_p5;
wire   [14:0] zext_ln252_fu_221_p1;
wire   [0:0] icmp_ln247_fu_255_p2;
wire   [5:0] add_ln245_fu_249_p2;
wire   [14:0] or_ln_mid1_fu_269_p5;
wire   [0:0] icmp_ln249_fu_295_p2;
wire   [0:0] xor_ln245_fu_289_p2;
wire   [7:0] select_ln245_fu_261_p3;
wire   [0:0] and_ln245_fu_301_p2;
wire   [0:0] or_ln247_fu_321_p2;
wire   [7:0] add_ln247_fu_315_p2;
wire   [9:0] shl_ln249_mid1_fu_335_p3;
wire   [14:0] select_ln245_1_fu_281_p3;
wire   [14:0] zext_ln252_1_fu_343_p1;
wire   [2:0] select_ln247_fu_327_p3;
wire   [14:0] add_ln252_3_fu_347_p2;
wire   [14:0] add_ln252_fu_225_p2;
wire   [12:0] tmp_1_fu_375_p4;
wire   [12:0] tmp_2_fu_385_p4;
wire   [12:0] tmp_fu_365_p4;
wire   [12:0] select_ln245_3_fu_395_p3;
wire   [12:0] select_ln247_2_fu_403_p3;
wire   [1:0] trunc_ln252_fu_361_p1;
wire   [18:0] shl_ln1_fu_411_p4;
wire   [63:0] zext_ln252_4_fu_421_p1;
wire   [63:0] add_ln252_1_fu_429_p2;
wire   [10:0] add_ln247_1_fu_450_p2;
wire   [4:0] trunc_ln252_7_fu_489_p3;
wire   [4:0] add_ln252_2_fu_500_p2;
wire   [31:0] zext_ln252_3_fu_505_p1;
wire   [7:0] shl_ln252_2_fu_515_p3;
wire   [255:0] zext_ln252_2_fu_496_p1;
wire   [255:0] zext_ln252_5_fu_523_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ViT_act_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_130 <= 15'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln245_fu_231_p2 == 1'd0))) begin
            indvar_flatten19_fu_130 <= add_ln245_1_fu_237_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_122 <= 11'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln245_fu_231_p2 == 1'd0))) begin
            indvar_flatten_fu_122 <= select_ln247_3_fu_456_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_patch_fu_118 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln245_fu_231_p2 == 1'd0))) begin
            k_patch_fu_118 <= select_ln247_1_fu_353_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            q_patch_block_fu_126 <= 6'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln245_fu_231_p2 == 1'd0))) begin
            q_patch_block_fu_126 <= select_ln245_2_fu_307_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            q_patch_offset_fu_114 <= 3'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln245_fu_231_p2 == 1'd0))) begin
            q_patch_offset_fu_114 <= add_ln249_fu_444_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        shl_ln252_1_reg_607 <= shl_ln252_1_fu_527_p2;
        shl_ln252_reg_602 <= shl_ln252_fu_509_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln245_fu_231_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln252_2_reg_592 <= trunc_ln252_2_fu_425_p1;
        trunc_ln252_8_reg_597 <= {{add_ln252_1_fu_429_p2[63:5]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln245_fu_231_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        attn_stream_blk_n = attn_stream_empty_n;
    end else begin
        attn_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        attn_stream_read = 1'b1;
    end else begin
        attn_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        inout1_blk_n_AW = m_axi_inout1_AWREADY;
    end else begin
        inout1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        inout1_blk_n_B = m_axi_inout1_BVALID;
    end else begin
        inout1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        inout1_blk_n_W = m_axi_inout1_WREADY;
    end else begin
        inout1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_inout1_AWVALID = 1'b1;
    end else begin
        m_axi_inout1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_inout1_BREADY = 1'b1;
    end else begin
        m_axi_inout1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_inout1_WVALID = 1'b1;
    end else begin
        m_axi_inout1_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln245_1_fu_237_p2 = (indvar_flatten19_fu_130 + 15'd1);

assign add_ln245_fu_249_p2 = (q_patch_block_fu_126 + 6'd1);

assign add_ln247_1_fu_450_p2 = (indvar_flatten_fu_122 + 11'd1);

assign add_ln247_fu_315_p2 = (select_ln245_fu_261_p3 + 8'd1);

assign add_ln249_fu_444_p2 = (select_ln247_fu_327_p3 + 3'd1);

assign add_ln252_1_fu_429_p2 = (attn_load + zext_ln252_4_fu_421_p1);

assign add_ln252_2_fu_500_p2 = (trunc_ln252_7_fu_489_p3 + trunc_ln252_1);

assign add_ln252_3_fu_347_p2 = (select_ln245_1_fu_281_p3 + zext_ln252_1_fu_343_p1);

assign add_ln252_fu_225_p2 = (or_ln_fu_201_p5 + zext_ln252_fu_221_p1);

assign and_ln245_fu_301_p2 = (xor_ln245_fu_289_p2 & icmp_ln249_fu_295_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((attn_stream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_inout1_BVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_inout1_BVALID == 1'b0)) | ((m_axi_inout1_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axi_inout1_AWREADY == 1'b0) | (attn_stream_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_inout1_BVALID == 1'b0)) | ((m_axi_inout1_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axi_inout1_AWREADY == 1'b0) | (attn_stream_empty_n == 1'b0))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (attn_stream_empty_n == 1'b0);
end

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (m_axi_inout1_BVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln245_fu_231_p2 = ((indvar_flatten19_fu_130 == 15'd17028) ? 1'b1 : 1'b0);

assign icmp_ln247_fu_255_p2 = ((indvar_flatten_fu_122 == 11'd516) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_295_p2 = ((q_patch_offset_fu_114 == 3'd4) ? 1'b1 : 1'b0);

assign m_axi_inout1_ARADDR = 64'd0;

assign m_axi_inout1_ARBURST = 2'd0;

assign m_axi_inout1_ARCACHE = 4'd0;

assign m_axi_inout1_ARID = 1'd0;

assign m_axi_inout1_ARLEN = 32'd0;

assign m_axi_inout1_ARLOCK = 2'd0;

assign m_axi_inout1_ARPROT = 3'd0;

assign m_axi_inout1_ARQOS = 4'd0;

assign m_axi_inout1_ARREGION = 4'd0;

assign m_axi_inout1_ARSIZE = 3'd0;

assign m_axi_inout1_ARUSER = 1'd0;

assign m_axi_inout1_ARVALID = 1'b0;

assign m_axi_inout1_AWADDR = sext_ln252_fu_533_p1;

assign m_axi_inout1_AWBURST = 2'd0;

assign m_axi_inout1_AWCACHE = 4'd0;

assign m_axi_inout1_AWID = 1'd0;

assign m_axi_inout1_AWLEN = 32'd1;

assign m_axi_inout1_AWLOCK = 2'd0;

assign m_axi_inout1_AWPROT = 3'd0;

assign m_axi_inout1_AWQOS = 4'd0;

assign m_axi_inout1_AWREGION = 4'd0;

assign m_axi_inout1_AWSIZE = 3'd0;

assign m_axi_inout1_AWUSER = 1'd0;

assign m_axi_inout1_RREADY = 1'b0;

assign m_axi_inout1_WDATA = shl_ln252_1_reg_607;

assign m_axi_inout1_WID = 1'd0;

assign m_axi_inout1_WLAST = 1'b0;

assign m_axi_inout1_WSTRB = shl_ln252_reg_602;

assign m_axi_inout1_WUSER = 1'd0;

assign or_ln247_fu_321_p2 = (icmp_ln247_fu_255_p2 | and_ln245_fu_301_p2);

assign or_ln_fu_201_p5 = {{{{q_patch_block_fu_126}, {1'd0}}, {q_patch_block_fu_126}}, {2'd0}};

assign or_ln_mid1_fu_269_p5 = {{{{add_ln245_fu_249_p2}, {1'd0}}, {add_ln245_fu_249_p2}}, {2'd0}};

assign select_ln245_1_fu_281_p3 = ((icmp_ln247_fu_255_p2[0:0] == 1'b1) ? or_ln_mid1_fu_269_p5 : or_ln_fu_201_p5);

assign select_ln245_2_fu_307_p3 = ((icmp_ln247_fu_255_p2[0:0] == 1'b1) ? add_ln245_fu_249_p2 : q_patch_block_fu_126);

assign select_ln245_3_fu_395_p3 = ((icmp_ln247_fu_255_p2[0:0] == 1'b1) ? tmp_1_fu_375_p4 : tmp_2_fu_385_p4);

assign select_ln245_fu_261_p3 = ((icmp_ln247_fu_255_p2[0:0] == 1'b1) ? 8'd0 : k_patch_fu_118);

assign select_ln247_1_fu_353_p3 = ((and_ln245_fu_301_p2[0:0] == 1'b1) ? add_ln247_fu_315_p2 : select_ln245_fu_261_p3);

assign select_ln247_2_fu_403_p3 = ((and_ln245_fu_301_p2[0:0] == 1'b1) ? tmp_fu_365_p4 : select_ln245_3_fu_395_p3);

assign select_ln247_3_fu_456_p3 = ((icmp_ln247_fu_255_p2[0:0] == 1'b1) ? 11'd1 : add_ln247_1_fu_450_p2);

assign select_ln247_fu_327_p3 = ((or_ln247_fu_321_p2[0:0] == 1'b1) ? 3'd0 : q_patch_offset_fu_114);

assign sext_ln252_fu_533_p1 = $signed(trunc_ln252_8_reg_597);

assign shl_ln1_fu_411_p4 = {{{select_ln247_2_fu_403_p3}, {trunc_ln252_fu_361_p1}}, {4'd0}};

assign shl_ln249_mid1_fu_335_p3 = {{add_ln247_fu_315_p2}, {2'd0}};

assign shl_ln252_1_fu_527_p2 = zext_ln252_2_fu_496_p1 << zext_ln252_5_fu_523_p1;

assign shl_ln252_2_fu_515_p3 = {{add_ln252_2_fu_500_p2}, {3'd0}};

assign shl_ln252_fu_509_p2 = 32'd65535 << zext_ln252_3_fu_505_p1;

assign shl_ln_fu_213_p3 = {{k_patch_fu_118}, {2'd0}};

assign tmp_1_fu_375_p4 = {{{add_ln245_fu_249_p2}, {1'd0}}, {add_ln245_fu_249_p2}};

assign tmp_2_fu_385_p4 = {{add_ln252_fu_225_p2[14:2]}};

assign tmp_fu_365_p4 = {{add_ln252_3_fu_347_p2[14:2]}};

assign trunc_ln252_2_fu_425_p1 = select_ln247_fu_327_p3[0:0];

assign trunc_ln252_7_fu_489_p3 = {{trunc_ln252_2_reg_592}, {4'd0}};

assign trunc_ln252_fu_361_p1 = select_ln247_fu_327_p3[1:0];

assign xor_ln245_fu_289_p2 = (icmp_ln247_fu_255_p2 ^ 1'd1);

assign zext_ln252_1_fu_343_p1 = shl_ln249_mid1_fu_335_p3;

assign zext_ln252_2_fu_496_p1 = attn_stream_dout;

assign zext_ln252_3_fu_505_p1 = add_ln252_2_fu_500_p2;

assign zext_ln252_4_fu_421_p1 = shl_ln1_fu_411_p4;

assign zext_ln252_5_fu_523_p1 = shl_ln252_2_fu_515_p3;

assign zext_ln252_fu_221_p1 = shl_ln_fu_213_p3;

endmodule //ViT_act_write_attn_Pipeline_ln245_for_each_q_patch_block_ln247_for_each_k_patch_ln249
